
/* Code automatically generated by Vult https://github.com/modlfo/vult */
#ifndef ENGINE_SYNTHFM_H
#define ENGINE_SYNTHFM_H
#include <stdint.h>
#include <math.h>
#include "vultin.h"
#include "engine_synthFM.tables.h"

typedef struct synthFM__tuple___real_real_real_real__ {
   fix16_t field_0;
   fix16_t field_1;
   fix16_t field_2;
   fix16_t field_3;
} synthFM__tuple___real_real_real_real__;

static_inline int synthFM_Wavetable_sin_wave_samples(){
   return 4096;
};

static_inline fix16_t synthFM_Wavetable_sin_wave(int channel, int index){
   if(channel == 0){
      return fix_wrap_array(synthFM_Wavetable_sin_wave_chan_0)[(index % 4096)];
   }
   return 0x0 /* 0.000000 */;
}

static_inline int synthFM_Wavetable_tri_wave_samples(){
   return 4096;
};

static_inline fix16_t synthFM_Wavetable_tri_wave(int channel, int index){
   if(channel == 0){
      return fix_wrap_array(synthFM_Wavetable_tri_wave_chan_0)[(index % 4096)];
   }
   return 0x0 /* 0.000000 */;
}

static_inline int synthFM_Wavetable_saw_wave_samples(){
   return 4096;
};

static_inline fix16_t synthFM_Wavetable_saw_wave(int channel, int index){
   if(channel == 0){
      return fix_wrap_array(synthFM_Wavetable_saw_wave_chan_0)[(index % 4096)];
   }
   return 0x0 /* 0.000000 */;
}

static_inline int synthFM_Wavetable_square_wave_samples(){
   return 4096;
};

static_inline fix16_t synthFM_Wavetable_square_wave(int channel, int index){
   if(channel == 0){
      return fix_wrap_array(synthFM_Wavetable_square_wave_chan_0)[(index % 4096)];
   }
   return 0x0 /* 0.000000 */;
}

static_inline int synthFM_Wavetable_tri_wave_bl_samples(){
   return 4096;
};

static_inline fix16_t synthFM_Wavetable_tri_wave_bl(int channel, int index){
   if(channel == 0){
      return fix_wrap_array(synthFM_Wavetable_tri_wave_bl_chan_0)[(index % 4096)];
   }
   return 0x0 /* 0.000000 */;
}

static_inline int synthFM_Wavetable_saw_wave_bl_samples(){
   return 4096;
};

static_inline fix16_t synthFM_Wavetable_saw_wave_bl(int channel, int index){
   if(channel == 0){
      return fix_wrap_array(synthFM_Wavetable_saw_wave_bl_chan_0)[(index % 4096)];
   }
   return 0x0 /* 0.000000 */;
}

static_inline int synthFM_Wavetable_square_wave_bl_samples(){
   return 4096;
};

static_inline fix16_t synthFM_Wavetable_square_wave_bl(int channel, int index){
   if(channel == 0){
      return fix_wrap_array(synthFM_Wavetable_square_wave_bl_chan_0)[(index % 4096)];
   }
   return 0x0 /* 0.000000 */;
}

fix16_t synthFM_Wavetable_getSample(int wavetableIdx, int index);

fix16_t synthFM_Wavetable_getSampleFrom(fix16_t (&wavetable)[4096], fix16_t index);

static_inline int synthFM_Wavetable_getNbWavetables(){
   return 8;
};

void synthFM_Wavetable_morphTo(fix16_t wavetableIdx, fix16_t phase, fix16_t (&buffer)[4096]);

static_inline void synthFM_Wavetable_bufferWavetable(fix16_t (&oBuff)[4096]){
}

static_inline int synthFM_Wavetable_bufferSize(){
   return 4096;
};

void synthFM_Wavetable_getRandomMorph(fix16_t (&oBuff)[4096]);

fix16_t synthFM_Wavetable_getRandRandomMorph(fix16_t (&oBuff)[4096]);

static_inline fix16_t synthFM_Util_noteToFrequency(int note){
   return fix_mul(0x217 /* 0.008176 */,fix_exp(fix_mul(0xec9 /* 0.057762 */,int_to_fix(note))));
};

static_inline fix16_t synthFM_Util_tonesToCoeff(fix16_t semitones){
   fix16_t log_base;
   log_base = 0xb172 /* 0.693147 */;
   return fix_exp(fix_mul(fix_mul(0x1555 /* 0.083333 */,log_base),semitones));
}

typedef struct synthFM_Util__ctx_type_2 {
   uint8_t pre;
} synthFM_Util__ctx_type_2;

typedef synthFM_Util__ctx_type_2 synthFM_Util_edge_type;

static_inline void synthFM_Util__ctx_type_2_init(synthFM_Util__ctx_type_2 &_output_){
   synthFM_Util__ctx_type_2 _ctx;
   _ctx.pre = false;
   _output_ = _ctx;
   return ;
}

static_inline void synthFM_Util_edge_init(synthFM_Util__ctx_type_2 &_output_){
   synthFM_Util__ctx_type_2_init(_output_);
   return ;
}

static_inline uint8_t synthFM_Util_edge(synthFM_Util__ctx_type_2 &_ctx, uint8_t x){
   uint8_t ret;
   ret = (x && bool_not(_ctx.pre));
   _ctx.pre = x;
   return ret;
}

static_inline fix16_t synthFM_Util_cubic_clipper(fix16_t x){
   if(x <= -0xaaaa /* -0.666667 */){
      return -0xaaaa /* -0.666667 */;
   }
   else
   {
      if(x >= 0xaaaa /* 0.666667 */){
         return 0xaaaa /* 0.666667 */;
      }
      else
      {
         return (x + fix_mul(fix_mul(fix_mul(-0x5555 /* -0.333333 */,x),x),x));
      }
   }
};

typedef struct synthFM_Util__ctx_type_4 {
   fix16_t pre_x;
} synthFM_Util__ctx_type_4;

typedef synthFM_Util__ctx_type_4 synthFM_Util_change_type;

static_inline void synthFM_Util__ctx_type_4_init(synthFM_Util__ctx_type_4 &_output_){
   synthFM_Util__ctx_type_4 _ctx;
   _ctx.pre_x = 0x0 /* 0.000000 */;
   _output_ = _ctx;
   return ;
}

static_inline void synthFM_Util_change_init(synthFM_Util__ctx_type_4 &_output_){
   synthFM_Util__ctx_type_4_init(_output_);
   return ;
}

static_inline uint8_t synthFM_Util_change(synthFM_Util__ctx_type_4 &_ctx, fix16_t x){
   uint8_t v;
   v = (_ctx.pre_x != x);
   _ctx.pre_x = x;
   return v;
}

typedef struct synthFM_Util__ctx_type_5 {
   fix16_t x;
} synthFM_Util__ctx_type_5;

typedef synthFM_Util__ctx_type_5 synthFM_Util_smooth_type;

static_inline void synthFM_Util__ctx_type_5_init(synthFM_Util__ctx_type_5 &_output_){
   synthFM_Util__ctx_type_5 _ctx;
   _ctx.x = 0x0 /* 0.000000 */;
   _output_ = _ctx;
   return ;
}

static_inline void synthFM_Util_smooth_init(synthFM_Util__ctx_type_5 &_output_){
   synthFM_Util__ctx_type_5_init(_output_);
   return ;
}

static_inline fix16_t synthFM_Util_smooth(synthFM_Util__ctx_type_5 &_ctx, fix16_t input, fix16_t coeff){
   _ctx.x = (_ctx.x + fix_mul(coeff,(input + (- _ctx.x))));
   return _ctx.x;
}

static_inline fix16_t synthFM_Util_velocityToLevel(int velocity){
   velocity = int_clip(velocity,0,127);
   return fix_mul(0x204 /* 0.007874 */,int_to_fix(velocity));
}

static_inline void synthFM_Buffer_buffer(fix16_t (&oBuff)[128]){
}

void synthFM_Buffer_buffer_large(fix16_t (&oBuff)[2048]);

typedef struct synthFM_OSC__ctx_type_0 {
   fix16_t stepRatio;
   fix16_t step;
   fix16_t rsize;
   fix16_t phase_base;
   fix16_t phase;
   fix16_t last_val_feedback;
   fix16_t fs;
   fix16_t freq;
} synthFM_OSC__ctx_type_0;

typedef synthFM_OSC__ctx_type_0 synthFM_OSC_process_type;

void synthFM_OSC__ctx_type_0_init(synthFM_OSC__ctx_type_0 &_output_);

static_inline void synthFM_OSC_process_init(synthFM_OSC__ctx_type_0 &_output_){
   synthFM_OSC__ctx_type_0_init(_output_);
   return ;
}

static_inline fix16_t synthFM_OSC_process(synthFM_OSC__ctx_type_0 &_ctx, fix16_t (&wavetable)[4096]){
   _ctx.phase = (_ctx.phase + _ctx.step);
   while(_ctx.phase > _ctx.rsize){
      _ctx.phase = (_ctx.phase + (- _ctx.rsize));
   }
   return synthFM_Wavetable_getSampleFrom(wavetable,(_ctx.phase + _ctx.phase_base));
}

typedef synthFM_OSC__ctx_type_0 synthFM_OSC_process_bufferTo_type;

static_inline void synthFM_OSC_process_bufferTo_init(synthFM_OSC__ctx_type_0 &_output_){
   synthFM_OSC__ctx_type_0_init(_output_);
   return ;
}

void synthFM_OSC_process_bufferTo(synthFM_OSC__ctx_type_0 &_ctx, fix16_t (&wavetable)[4096], int nb, fix16_t (&env)[128], fix16_t (&phase_shift)[128], fix16_t (&phase_env)[128], fix16_t phase_shift_level, uint8_t shift_level, fix16_t (&oBuffer)[128]);

typedef synthFM_OSC__ctx_type_0 synthFM_OSC_process_bufferTo_simple_type;

static_inline void synthFM_OSC_process_bufferTo_simple_init(synthFM_OSC__ctx_type_0 &_output_){
   synthFM_OSC__ctx_type_0_init(_output_);
   return ;
}

void synthFM_OSC_process_bufferTo_simple(synthFM_OSC__ctx_type_0 &_ctx, fix16_t (&wavetable)[4096], int nb, fix16_t (&env)[128], fix16_t (&oBuffer)[128]);

typedef synthFM_OSC__ctx_type_0 synthFM_OSC_process_bufferTo_feedback_type;

static_inline void synthFM_OSC_process_bufferTo_feedback_init(synthFM_OSC__ctx_type_0 &_output_){
   synthFM_OSC__ctx_type_0_init(_output_);
   return ;
}

void synthFM_OSC_process_bufferTo_feedback(synthFM_OSC__ctx_type_0 &_ctx, fix16_t (&wavetable)[4096], int nb, fix16_t (&env)[128], fix16_t feedback, fix16_t (&oBuffer)[128]);

typedef synthFM_OSC__ctx_type_0 synthFM_OSC_process_bufferTo_simplest_type;

static_inline void synthFM_OSC_process_bufferTo_simplest_init(synthFM_OSC__ctx_type_0 &_output_){
   synthFM_OSC__ctx_type_0_init(_output_);
   return ;
}

void synthFM_OSC_process_bufferTo_simplest(synthFM_OSC__ctx_type_0 &_ctx, fix16_t (&wavetable)[4096], int nb, fix16_t (&oBuffer)[128]);

typedef synthFM_OSC__ctx_type_0 synthFM_OSC_updateStep_type;

static_inline void synthFM_OSC_updateStep_init(synthFM_OSC__ctx_type_0 &_output_){
   synthFM_OSC__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_OSC_updateStep(synthFM_OSC__ctx_type_0 &_ctx){
   _ctx.step = fix_mul(_ctx.freq,_ctx.stepRatio);
};

typedef synthFM_OSC__ctx_type_0 synthFM_OSC_setSamplerate_type;

static_inline void synthFM_OSC_setSamplerate_init(synthFM_OSC__ctx_type_0 &_output_){
   synthFM_OSC__ctx_type_0_init(_output_);
   return ;
}

void synthFM_OSC_setSamplerate(synthFM_OSC__ctx_type_0 &_ctx, fix16_t newFs);

typedef synthFM_OSC__ctx_type_0 synthFM_OSC_setFrequency_type;

static_inline void synthFM_OSC_setFrequency_init(synthFM_OSC__ctx_type_0 &_output_){
   synthFM_OSC__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_OSC_setFrequency(synthFM_OSC__ctx_type_0 &_ctx, fix16_t newFreq){
   _ctx.freq = newFreq;
   synthFM_OSC_updateStep(_ctx);
}

typedef synthFM_OSC__ctx_type_0 synthFM_OSC_setPhase_type;

static_inline void synthFM_OSC_setPhase_init(synthFM_OSC__ctx_type_0 &_output_){
   synthFM_OSC__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_OSC_setPhase(synthFM_OSC__ctx_type_0 &_ctx, fix16_t newPhase){
   _ctx.phase_base = newPhase;
};

typedef synthFM_OSC__ctx_type_0 synthFM_OSC_resetPhase_type;

static_inline void synthFM_OSC_resetPhase_init(synthFM_OSC__ctx_type_0 &_output_){
   synthFM_OSC__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_OSC_resetPhase(synthFM_OSC__ctx_type_0 &_ctx){
   _ctx.phase = 0x0 /* 0.000000 */;
   _ctx.phase_base = 0x0 /* 0.000000 */;
   _ctx.last_val_feedback = 0x0 /* 0.000000 */;
}

typedef synthFM_OSC__ctx_type_0 synthFM_OSC_getSize_type;

static_inline void synthFM_OSC_getSize_init(synthFM_OSC__ctx_type_0 &_output_){
   synthFM_OSC__ctx_type_0_init(_output_);
   return ;
}

static_inline fix16_t synthFM_OSC_getSize(synthFM_OSC__ctx_type_0 &_ctx){
   return _ctx.rsize;
};

typedef synthFM_OSC__ctx_type_0 synthFM_OSC_default_type;

static_inline void synthFM_OSC_default_init(synthFM_OSC__ctx_type_0 &_output_){
   synthFM_OSC__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_OSC_default(synthFM_OSC__ctx_type_0 &_ctx){
   _ctx.rsize = 0x10000000 /* 4096.000000 */;
   synthFM_OSC_setSamplerate(_ctx,0x2c1999 /* 44.100000 */);
   synthFM_OSC_setFrequency(_ctx,0x70a3 /* 0.440000 */);
}

typedef struct synthFM_OSC__ctx_type_1 {
   synthFM_OSC__ctx_type_0 _inst4ad;
   synthFM_OSC__ctx_type_0 _inst35f;
   synthFM_OSC__ctx_type_0 _inst2a3;
   synthFM_OSC__ctx_type_0 _inst133;
} synthFM_OSC__ctx_type_1;

typedef synthFM_OSC__ctx_type_1 synthFM_OSC_dummy_type;

void synthFM_OSC__ctx_type_1_init(synthFM_OSC__ctx_type_1 &_output_);

static_inline void synthFM_OSC_dummy_init(synthFM_OSC__ctx_type_1 &_output_){
   synthFM_OSC__ctx_type_1_init(_output_);
   return ;
}

void synthFM_OSC_dummy(synthFM_OSC__ctx_type_1 &_ctx, fix16_t (&wavetable)[4096]);

typedef struct synthFM_Notes__ctx_type_0 {
   uint8_t poly;
   int notes[128];
   int nb_notes;
   int last_notes[128];
   uint8_t allowDuplicates;
} synthFM_Notes__ctx_type_0;

typedef synthFM_Notes__ctx_type_0 synthFM_Notes_setPoly_type;

void synthFM_Notes__ctx_type_0_init(synthFM_Notes__ctx_type_0 &_output_);

static_inline void synthFM_Notes_setPoly_init(synthFM_Notes__ctx_type_0 &_output_){
   synthFM_Notes__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Notes_setPoly(synthFM_Notes__ctx_type_0 &_ctx, uint8_t flag){
   _ctx.poly = flag;
};

typedef synthFM_Notes__ctx_type_0 synthFM_Notes_getPoly_type;

static_inline void synthFM_Notes_getPoly_init(synthFM_Notes__ctx_type_0 &_output_){
   synthFM_Notes__ctx_type_0_init(_output_);
   return ;
}

static_inline uint8_t synthFM_Notes_getPoly(synthFM_Notes__ctx_type_0 &_ctx){
   return _ctx.poly;
};

typedef synthFM_Notes__ctx_type_0 synthFM_Notes_setAllowDuplicates_type;

static_inline void synthFM_Notes_setAllowDuplicates_init(synthFM_Notes__ctx_type_0 &_output_){
   synthFM_Notes__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Notes_setAllowDuplicates(synthFM_Notes__ctx_type_0 &_ctx, uint8_t flag){
   _ctx.allowDuplicates = flag;
};

typedef synthFM_Notes__ctx_type_0 synthFM_Notes_default_type;

static_inline void synthFM_Notes_default_init(synthFM_Notes__ctx_type_0 &_output_){
   synthFM_Notes__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Notes_default(synthFM_Notes__ctx_type_0 &_ctx){
   synthFM_Notes_setPoly(_ctx,false);
   synthFM_Notes_setAllowDuplicates(_ctx,false);
}

typedef synthFM_Notes__ctx_type_0 synthFM_Notes_nbNotes_type;

static_inline void synthFM_Notes_nbNotes_init(synthFM_Notes__ctx_type_0 &_output_){
   synthFM_Notes__ctx_type_0_init(_output_);
   return ;
}

static_inline int synthFM_Notes_nbNotes(synthFM_Notes__ctx_type_0 &_ctx){
   return _ctx.nb_notes;
};

typedef synthFM_Notes__ctx_type_0 synthFM_Notes_firstNote_type;

static_inline void synthFM_Notes_firstNote_init(synthFM_Notes__ctx_type_0 &_output_){
   synthFM_Notes__ctx_type_0_init(_output_);
   return ;
}

int synthFM_Notes_firstNote(synthFM_Notes__ctx_type_0 &_ctx);

typedef synthFM_Notes__ctx_type_0 synthFM_Notes_lastNote_type;

static_inline void synthFM_Notes_lastNote_init(synthFM_Notes__ctx_type_0 &_output_){
   synthFM_Notes__ctx_type_0_init(_output_);
   return ;
}

int synthFM_Notes_lastNote(synthFM_Notes__ctx_type_0 &_ctx);

typedef synthFM_Notes__ctx_type_0 synthFM_Notes_noteOff_type;

static_inline void synthFM_Notes_noteOff_init(synthFM_Notes__ctx_type_0 &_output_){
   synthFM_Notes__ctx_type_0_init(_output_);
   return ;
}

uint8_t synthFM_Notes_noteOff(synthFM_Notes__ctx_type_0 &_ctx, int note, int channel);

typedef synthFM_Notes__ctx_type_0 synthFM_Notes_noteOn_type;

static_inline void synthFM_Notes_noteOn_init(synthFM_Notes__ctx_type_0 &_output_){
   synthFM_Notes__ctx_type_0_init(_output_);
   return ;
}

uint8_t synthFM_Notes_noteOn(synthFM_Notes__ctx_type_0 &_ctx, int note, int velocity, int channel);

typedef struct synthFM_ADSR__ctx_type_0 {
   fix16_t getMaxValues_ret_3;
   fix16_t getMaxValues_ret_2;
   fix16_t getMaxValues_ret_1;
   fix16_t getMaxValues_ret_0;
} synthFM_ADSR__ctx_type_0;

typedef synthFM_ADSR__ctx_type_0 synthFM_ADSR_getMaxValues_type;

void synthFM_ADSR__ctx_type_0_init(synthFM_ADSR__ctx_type_0 &_output_);

static_inline void synthFM_ADSR_getMaxValues_init(synthFM_ADSR__ctx_type_0 &_output_){
   synthFM_ADSR__ctx_type_0_init(_output_);
   return ;
}

void synthFM_ADSR_getMaxValues(synthFM_ADSR__ctx_type_0 &_ctx);

typedef synthFM_ADSR__ctx_type_0 synthFM_ADSR_getMaxValues_ret_0_type;

static_inline void synthFM_ADSR_getMaxValues_ret_0_init(synthFM_ADSR__ctx_type_0 &_output_){
   synthFM_ADSR__ctx_type_0_init(_output_);
   return ;
}

static_inline fix16_t synthFM_ADSR_getMaxValues_ret_0(synthFM_ADSR__ctx_type_0 &_ctx){
   return _ctx.getMaxValues_ret_0;
};

typedef synthFM_ADSR__ctx_type_0 synthFM_ADSR_getMaxValues_ret_1_type;

static_inline void synthFM_ADSR_getMaxValues_ret_1_init(synthFM_ADSR__ctx_type_0 &_output_){
   synthFM_ADSR__ctx_type_0_init(_output_);
   return ;
}

static_inline fix16_t synthFM_ADSR_getMaxValues_ret_1(synthFM_ADSR__ctx_type_0 &_ctx){
   return _ctx.getMaxValues_ret_1;
};

typedef synthFM_ADSR__ctx_type_0 synthFM_ADSR_getMaxValues_ret_2_type;

static_inline void synthFM_ADSR_getMaxValues_ret_2_init(synthFM_ADSR__ctx_type_0 &_output_){
   synthFM_ADSR__ctx_type_0_init(_output_);
   return ;
}

static_inline fix16_t synthFM_ADSR_getMaxValues_ret_2(synthFM_ADSR__ctx_type_0 &_ctx){
   return _ctx.getMaxValues_ret_2;
};

typedef synthFM_ADSR__ctx_type_0 synthFM_ADSR_getMaxValues_ret_3_type;

static_inline void synthFM_ADSR_getMaxValues_ret_3_init(synthFM_ADSR__ctx_type_0 &_output_){
   synthFM_ADSR__ctx_type_0_init(_output_);
   return ;
}

static_inline fix16_t synthFM_ADSR_getMaxValues_ret_3(synthFM_ADSR__ctx_type_0 &_ctx){
   return _ctx.getMaxValues_ret_3;
};

typedef struct synthFM_ADSR__ctx_type_1 {
   synthFM_ADSR__ctx_type_0 _inst173;
} synthFM_ADSR__ctx_type_1;

typedef synthFM_ADSR__ctx_type_1 synthFM_ADSR_getMaxAttack_type;

static_inline void synthFM_ADSR__ctx_type_1_init(synthFM_ADSR__ctx_type_1 &_output_){
   synthFM_ADSR__ctx_type_1 _ctx;
   synthFM_ADSR__ctx_type_0_init(_ctx._inst173);
   _output_ = _ctx;
   return ;
}

static_inline void synthFM_ADSR_getMaxAttack_init(synthFM_ADSR__ctx_type_1 &_output_){
   synthFM_ADSR__ctx_type_1_init(_output_);
   return ;
}

fix16_t synthFM_ADSR_getMaxAttack(synthFM_ADSR__ctx_type_1 &_ctx);

typedef struct synthFM_ADSR__ctx_type_2 {
   synthFM_ADSR__ctx_type_0 _inst173;
} synthFM_ADSR__ctx_type_2;

typedef synthFM_ADSR__ctx_type_2 synthFM_ADSR_getMaxDecay_type;

static_inline void synthFM_ADSR__ctx_type_2_init(synthFM_ADSR__ctx_type_2 &_output_){
   synthFM_ADSR__ctx_type_2 _ctx;
   synthFM_ADSR__ctx_type_0_init(_ctx._inst173);
   _output_ = _ctx;
   return ;
}

static_inline void synthFM_ADSR_getMaxDecay_init(synthFM_ADSR__ctx_type_2 &_output_){
   synthFM_ADSR__ctx_type_2_init(_output_);
   return ;
}

fix16_t synthFM_ADSR_getMaxDecay(synthFM_ADSR__ctx_type_2 &_ctx);

typedef struct synthFM_ADSR__ctx_type_3 {
   synthFM_ADSR__ctx_type_0 _inst173;
} synthFM_ADSR__ctx_type_3;

typedef synthFM_ADSR__ctx_type_3 synthFM_ADSR_getMaxSustain_type;

static_inline void synthFM_ADSR__ctx_type_3_init(synthFM_ADSR__ctx_type_3 &_output_){
   synthFM_ADSR__ctx_type_3 _ctx;
   synthFM_ADSR__ctx_type_0_init(_ctx._inst173);
   _output_ = _ctx;
   return ;
}

static_inline void synthFM_ADSR_getMaxSustain_init(synthFM_ADSR__ctx_type_3 &_output_){
   synthFM_ADSR__ctx_type_3_init(_output_);
   return ;
}

fix16_t synthFM_ADSR_getMaxSustain(synthFM_ADSR__ctx_type_3 &_ctx);

typedef struct synthFM_ADSR__ctx_type_4 {
   synthFM_ADSR__ctx_type_0 _inst173;
} synthFM_ADSR__ctx_type_4;

typedef synthFM_ADSR__ctx_type_4 synthFM_ADSR_getMaxRelease_type;

static_inline void synthFM_ADSR__ctx_type_4_init(synthFM_ADSR__ctx_type_4 &_output_){
   synthFM_ADSR__ctx_type_4 _ctx;
   synthFM_ADSR__ctx_type_0_init(_ctx._inst173);
   _output_ = _ctx;
   return ;
}

static_inline void synthFM_ADSR_getMaxRelease_init(synthFM_ADSR__ctx_type_4 &_output_){
   synthFM_ADSR__ctx_type_4_init(_output_);
   return ;
}

fix16_t synthFM_ADSR_getMaxRelease(synthFM_ADSR__ctx_type_4 &_ctx);

typedef struct synthFM_ADSR__ctx_type_5 {
   fix16_t getMinValues_ret_3;
   fix16_t getMinValues_ret_2;
   fix16_t getMinValues_ret_1;
   fix16_t getMinValues_ret_0;
} synthFM_ADSR__ctx_type_5;

typedef synthFM_ADSR__ctx_type_5 synthFM_ADSR_getMinValues_type;

void synthFM_ADSR__ctx_type_5_init(synthFM_ADSR__ctx_type_5 &_output_);

static_inline void synthFM_ADSR_getMinValues_init(synthFM_ADSR__ctx_type_5 &_output_){
   synthFM_ADSR__ctx_type_5_init(_output_);
   return ;
}

void synthFM_ADSR_getMinValues(synthFM_ADSR__ctx_type_5 &_ctx);

typedef synthFM_ADSR__ctx_type_5 synthFM_ADSR_getMinValues_ret_0_type;

static_inline void synthFM_ADSR_getMinValues_ret_0_init(synthFM_ADSR__ctx_type_5 &_output_){
   synthFM_ADSR__ctx_type_5_init(_output_);
   return ;
}

static_inline fix16_t synthFM_ADSR_getMinValues_ret_0(synthFM_ADSR__ctx_type_5 &_ctx){
   return _ctx.getMinValues_ret_0;
};

typedef synthFM_ADSR__ctx_type_5 synthFM_ADSR_getMinValues_ret_1_type;

static_inline void synthFM_ADSR_getMinValues_ret_1_init(synthFM_ADSR__ctx_type_5 &_output_){
   synthFM_ADSR__ctx_type_5_init(_output_);
   return ;
}

static_inline fix16_t synthFM_ADSR_getMinValues_ret_1(synthFM_ADSR__ctx_type_5 &_ctx){
   return _ctx.getMinValues_ret_1;
};

typedef synthFM_ADSR__ctx_type_5 synthFM_ADSR_getMinValues_ret_2_type;

static_inline void synthFM_ADSR_getMinValues_ret_2_init(synthFM_ADSR__ctx_type_5 &_output_){
   synthFM_ADSR__ctx_type_5_init(_output_);
   return ;
}

static_inline fix16_t synthFM_ADSR_getMinValues_ret_2(synthFM_ADSR__ctx_type_5 &_ctx){
   return _ctx.getMinValues_ret_2;
};

typedef synthFM_ADSR__ctx_type_5 synthFM_ADSR_getMinValues_ret_3_type;

static_inline void synthFM_ADSR_getMinValues_ret_3_init(synthFM_ADSR__ctx_type_5 &_output_){
   synthFM_ADSR__ctx_type_5_init(_output_);
   return ;
}

static_inline fix16_t synthFM_ADSR_getMinValues_ret_3(synthFM_ADSR__ctx_type_5 &_ctx){
   return _ctx.getMinValues_ret_3;
};

typedef struct synthFM_ADSR__ctx_type_6 {
   synthFM_ADSR__ctx_type_5 _inst1d6;
} synthFM_ADSR__ctx_type_6;

typedef synthFM_ADSR__ctx_type_6 synthFM_ADSR_getMinAttack_type;

static_inline void synthFM_ADSR__ctx_type_6_init(synthFM_ADSR__ctx_type_6 &_output_){
   synthFM_ADSR__ctx_type_6 _ctx;
   synthFM_ADSR__ctx_type_5_init(_ctx._inst1d6);
   _output_ = _ctx;
   return ;
}

static_inline void synthFM_ADSR_getMinAttack_init(synthFM_ADSR__ctx_type_6 &_output_){
   synthFM_ADSR__ctx_type_6_init(_output_);
   return ;
}

fix16_t synthFM_ADSR_getMinAttack(synthFM_ADSR__ctx_type_6 &_ctx);

typedef struct synthFM_ADSR__ctx_type_7 {
   synthFM_ADSR__ctx_type_5 _inst1d6;
} synthFM_ADSR__ctx_type_7;

typedef synthFM_ADSR__ctx_type_7 synthFM_ADSR_getMinDecay_type;

static_inline void synthFM_ADSR__ctx_type_7_init(synthFM_ADSR__ctx_type_7 &_output_){
   synthFM_ADSR__ctx_type_7 _ctx;
   synthFM_ADSR__ctx_type_5_init(_ctx._inst1d6);
   _output_ = _ctx;
   return ;
}

static_inline void synthFM_ADSR_getMinDecay_init(synthFM_ADSR__ctx_type_7 &_output_){
   synthFM_ADSR__ctx_type_7_init(_output_);
   return ;
}

fix16_t synthFM_ADSR_getMinDecay(synthFM_ADSR__ctx_type_7 &_ctx);

typedef struct synthFM_ADSR__ctx_type_8 {
   synthFM_ADSR__ctx_type_5 _inst1d6;
} synthFM_ADSR__ctx_type_8;

typedef synthFM_ADSR__ctx_type_8 synthFM_ADSR_getMinSustain_type;

static_inline void synthFM_ADSR__ctx_type_8_init(synthFM_ADSR__ctx_type_8 &_output_){
   synthFM_ADSR__ctx_type_8 _ctx;
   synthFM_ADSR__ctx_type_5_init(_ctx._inst1d6);
   _output_ = _ctx;
   return ;
}

static_inline void synthFM_ADSR_getMinSustain_init(synthFM_ADSR__ctx_type_8 &_output_){
   synthFM_ADSR__ctx_type_8_init(_output_);
   return ;
}

fix16_t synthFM_ADSR_getMinSustain(synthFM_ADSR__ctx_type_8 &_ctx);

typedef struct synthFM_ADSR__ctx_type_9 {
   synthFM_ADSR__ctx_type_5 _inst1d6;
} synthFM_ADSR__ctx_type_9;

typedef synthFM_ADSR__ctx_type_9 synthFM_ADSR_getMinRelease_type;

static_inline void synthFM_ADSR__ctx_type_9_init(synthFM_ADSR__ctx_type_9 &_output_){
   synthFM_ADSR__ctx_type_9 _ctx;
   synthFM_ADSR__ctx_type_5_init(_ctx._inst1d6);
   _output_ = _ctx;
   return ;
}

static_inline void synthFM_ADSR_getMinRelease_init(synthFM_ADSR__ctx_type_9 &_output_){
   synthFM_ADSR__ctx_type_9_init(_output_);
   return ;
}

fix16_t synthFM_ADSR_getMinRelease(synthFM_ADSR__ctx_type_9 &_ctx);

typedef struct synthFM_ADSR__ctx_type_10 {
   fix16_t target;
   fix16_t step;
   int state;
   fix16_t s;
   uint8_t retrigger;
   fix16_t r_step;
   fix16_t r;
   fix16_t out;
   fix16_t fs;
   fix16_t d_step;
   fix16_t d;
   fix16_t a_target;
   fix16_t a_step;
   fix16_t a;
   synthFM_ADSR__ctx_type_5 _inst38d6;
   synthFM_ADSR__ctx_type_0 _inst3773;
   synthFM_ADSR__ctx_type_5 _inst33d6;
   synthFM_Util__ctx_type_2 _inst1851;
   synthFM_Util__ctx_type_2 _inst151;
   synthFM_ADSR__ctx_type_9 _inst12c;
} synthFM_ADSR__ctx_type_10;

typedef synthFM_ADSR__ctx_type_10 synthFM_ADSR_stepToRelease_type;

void synthFM_ADSR__ctx_type_10_init(synthFM_ADSR__ctx_type_10 &_output_);

static_inline void synthFM_ADSR_stepToRelease_init(synthFM_ADSR__ctx_type_10 &_output_){
   synthFM_ADSR__ctx_type_10_init(_output_);
   return ;
}

static_inline fix16_t synthFM_ADSR_stepToRelease(synthFM_ADSR__ctx_type_10 &_ctx, fix16_t curr_val){
   return fix_div((- curr_val),fix_mul(_ctx.fs,fix_clip(_ctx.r,synthFM_ADSR_getMinRelease(_ctx._inst12c),_ctx.r)));
};

typedef synthFM_ADSR__ctx_type_10 synthFM_ADSR_process_type;

static_inline void synthFM_ADSR_process_init(synthFM_ADSR__ctx_type_10 &_output_){
   synthFM_ADSR__ctx_type_10_init(_output_);
   return ;
}

fix16_t synthFM_ADSR_process(synthFM_ADSR__ctx_type_10 &_ctx, uint8_t bgate);

typedef synthFM_ADSR__ctx_type_10 synthFM_ADSR_process_bufferTo_type;

static_inline void synthFM_ADSR_process_bufferTo_init(synthFM_ADSR__ctx_type_10 &_output_){
   synthFM_ADSR__ctx_type_10_init(_output_);
   return ;
}

uint8_t synthFM_ADSR_process_bufferTo(synthFM_ADSR__ctx_type_10 &_ctx, uint8_t bgate, int nb, fix16_t (&oBuffer)[128]);

typedef synthFM_ADSR__ctx_type_10 synthFM_ADSR_updateSteps_type;

static_inline void synthFM_ADSR_updateSteps_init(synthFM_ADSR__ctx_type_10 &_output_){
   synthFM_ADSR__ctx_type_10_init(_output_);
   return ;
}

void synthFM_ADSR_updateSteps(synthFM_ADSR__ctx_type_10 &_ctx);

typedef synthFM_ADSR__ctx_type_10 synthFM_ADSR_setSamplerate_type;

static_inline void synthFM_ADSR_setSamplerate_init(synthFM_ADSR__ctx_type_10 &_output_){
   synthFM_ADSR__ctx_type_10_init(_output_);
   return ;
}

static_inline void synthFM_ADSR_setSamplerate(synthFM_ADSR__ctx_type_10 &_ctx, fix16_t newFs){
   if(newFs > 0x0 /* 0.000000 */){
      _ctx.fs = newFs;
   }
   synthFM_ADSR_updateSteps(_ctx);
}

typedef synthFM_ADSR__ctx_type_10 synthFM_ADSR_config_type;

static_inline void synthFM_ADSR_config_init(synthFM_ADSR__ctx_type_10 &_output_){
   synthFM_ADSR__ctx_type_10_init(_output_);
   return ;
}

void synthFM_ADSR_config(synthFM_ADSR__ctx_type_10 &_ctx, fix16_t newA, fix16_t newD, fix16_t newS, fix16_t newR);

typedef synthFM_ADSR__ctx_type_10 synthFM_ADSR_retrig_type;

static_inline void synthFM_ADSR_retrig_init(synthFM_ADSR__ctx_type_10 &_output_){
   synthFM_ADSR__ctx_type_10_init(_output_);
   return ;
}

static_inline void synthFM_ADSR_retrig(synthFM_ADSR__ctx_type_10 &_ctx){
   _ctx.retrigger = true;
};

typedef synthFM_ADSR__ctx_type_10 synthFM_ADSR_default_type;

static_inline void synthFM_ADSR_default_init(synthFM_ADSR__ctx_type_10 &_output_){
   synthFM_ADSR__ctx_type_10_init(_output_);
   return ;
}

static_inline void synthFM_ADSR_default(synthFM_ADSR__ctx_type_10 &_ctx){
   _ctx.a_target = 0x10000 /* 1.000000 */;
   synthFM_ADSR_setSamplerate(_ctx,0x2c1999 /* 44.100000 */);
   synthFM_ADSR_config(_ctx,0x0 /* 0.000000 */,0x0 /* 0.000000 */,0x8000 /* 0.500000 */,0x0 /* 0.000000 */);
}

typedef struct synthFM_ADSR__ctx_type_11 {
   synthFM_ADSR__ctx_type_10 _inst182;
} synthFM_ADSR__ctx_type_11;

typedef synthFM_ADSR__ctx_type_11 synthFM_ADSR_dummy_type;

static_inline void synthFM_ADSR__ctx_type_11_init(synthFM_ADSR__ctx_type_11 &_output_){
   synthFM_ADSR__ctx_type_11 _ctx;
   synthFM_ADSR__ctx_type_10_init(_ctx._inst182);
   _output_ = _ctx;
   return ;
}

static_inline void synthFM_ADSR_dummy_init(synthFM_ADSR__ctx_type_11 &_output_){
   synthFM_ADSR__ctx_type_11_init(_output_);
   return ;
}

static_inline void synthFM_ADSR_dummy(synthFM_ADSR__ctx_type_11 &_ctx){
   fix16_t buff[128];
   synthFM_Buffer_buffer(buff);
   synthFM_ADSR_process_bufferTo(_ctx._inst182,false,0,buff);
}

typedef struct synthFM_FM__ctx_type_0 {
   fix16_t target_level;
   uint8_t sustaining;
   uint8_t sustain;
   synthFM_Notes__ctx_type_0 playingnotes;
   int n;
   synthFM_ADSR__ctx_type_10 modulatoradsr;
   uint8_t modulator_target_level;
   fix16_t modulator_phase_shift;
   fix16_t modulator_phase_range;
   fix16_t modulator_max_phase;
   fix16_t modulator_level_coeff;
   fix16_t modulator_level;
   fix16_t modulator_feedback;
   fix16_t modulator_env;
   fix16_t modulatorRatio;
   synthFM_OSC__ctx_type_0 modulator;
   fix16_t level_step_ref;
   fix16_t level_step;
   fix16_t level;
   uint8_t gate;
   fix16_t fs;
   fix16_t freq;
   uint8_t env_modulator_idle;
   int env_decimation_factor;
   uint8_t env_carrier_idle;
   synthFM_ADSR__ctx_type_10 carrieradsr;
   fix16_t carrier_phase_range;
   fix16_t carrier_max_phase;
   fix16_t carrier_env;
   fix16_t carrierRatio;
   synthFM_OSC__ctx_type_0 carrier;
   fix16_t buffer_modulator_env[128];
   fix16_t buffer_modulator[128];
   fix16_t buffer_carrier_env[128];
   fix16_t bend;
} synthFM_FM__ctx_type_0;

typedef synthFM_FM__ctx_type_0 synthFM_FM_process_type;

void synthFM_FM__ctx_type_0_init(synthFM_FM__ctx_type_0 &_output_);

static_inline void synthFM_FM_process_init(synthFM_FM__ctx_type_0 &_output_){
   synthFM_FM__ctx_type_0_init(_output_);
   return ;
}

fix16_t synthFM_FM_process(synthFM_FM__ctx_type_0 &_ctx, fix16_t (&wavetable_modulator)[4096], fix16_t (&wavetable_carrier)[4096]);

typedef synthFM_FM__ctx_type_0 synthFM_FM_process_bufferTo_type;

static_inline void synthFM_FM_process_bufferTo_init(synthFM_FM__ctx_type_0 &_output_){
   synthFM_FM__ctx_type_0_init(_output_);
   return ;
}

void synthFM_FM_process_bufferTo(synthFM_FM__ctx_type_0 &_ctx, fix16_t (&wavetable_modulator)[4096], fix16_t (&wavetable_carrier)[4096], int nb, fix16_t (&oBuffer)[128]);

typedef synthFM_FM__ctx_type_0 synthFM_FM__updateLevelStep_type;

static_inline void synthFM_FM__updateLevelStep_init(synthFM_FM__ctx_type_0 &_output_){
   synthFM_FM__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_FM__updateLevelStep(synthFM_FM__ctx_type_0 &_ctx){
   _ctx.level_step_ref = fix_div(0x10000 /* 1.000000 */,_ctx.fs);
   if(_ctx.env_decimation_factor > 0){
      _ctx.level_step_ref = fix_mul(_ctx.level_step_ref,int_to_fix(_ctx.env_decimation_factor));
   }
}

typedef synthFM_FM__ctx_type_0 synthFM_FM_setEnvDecimationFactor_type;

static_inline void synthFM_FM_setEnvDecimationFactor_init(synthFM_FM__ctx_type_0 &_output_){
   synthFM_FM__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_FM_setEnvDecimationFactor(synthFM_FM__ctx_type_0 &_ctx, int newFactor){
   _ctx.env_decimation_factor = int_clip(newFactor,0,1000);
   synthFM_FM__updateLevelStep(_ctx);
}

typedef synthFM_FM__ctx_type_0 synthFM_FM_setSamplerate_type;

static_inline void synthFM_FM_setSamplerate_init(synthFM_FM__ctx_type_0 &_output_){
   synthFM_FM__ctx_type_0_init(_output_);
   return ;
}

void synthFM_FM_setSamplerate(synthFM_FM__ctx_type_0 &_ctx, fix16_t newFs);

typedef synthFM_FM__ctx_type_0 synthFM_FM_setLevel_type;

static_inline void synthFM_FM_setLevel_init(synthFM_FM__ctx_type_0 &_output_){
   synthFM_FM__ctx_type_0_init(_output_);
   return ;
}

void synthFM_FM_setLevel(synthFM_FM__ctx_type_0 &_ctx, fix16_t newLevel);

typedef synthFM_FM__ctx_type_0 synthFM_FM_setCarrierRatio_type;

static_inline void synthFM_FM_setCarrierRatio_init(synthFM_FM__ctx_type_0 &_output_){
   synthFM_FM__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_FM_setCarrierRatio(synthFM_FM__ctx_type_0 &_ctx, fix16_t ratio){
   _ctx.carrierRatio = ratio;
   if(_ctx.carrierRatio < 0x0 /* 0.000000 */){
      synthFM_OSC_setFrequency(_ctx.carrier,(- _ctx.carrierRatio));
   }
}

typedef synthFM_FM__ctx_type_0 synthFM_FM_setModulatorRatio_type;

static_inline void synthFM_FM_setModulatorRatio_init(synthFM_FM__ctx_type_0 &_output_){
   synthFM_FM__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_FM_setModulatorRatio(synthFM_FM__ctx_type_0 &_ctx, fix16_t ratio){
   _ctx.modulatorRatio = ratio;
   if(_ctx.modulatorRatio < 0x0 /* 0.000000 */){
      synthFM_OSC_setFrequency(_ctx.modulator,(- _ctx.modulatorRatio));
   }
}

typedef synthFM_FM__ctx_type_0 synthFM_FM_setModulatorLevel_type;

static_inline void synthFM_FM_setModulatorLevel_init(synthFM_FM__ctx_type_0 &_output_){
   synthFM_FM__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_FM_setModulatorLevel(synthFM_FM__ctx_type_0 &_ctx, fix16_t newLevel){
   _ctx.modulator_level = newLevel;
   _ctx.carrier_max_phase = (synthFM_OSC_getSize(_ctx.carrier) << 1);
   _ctx.carrier_phase_range = fix_mul(_ctx.carrier_max_phase,_ctx.modulator_level);
   _ctx.modulator_level_coeff = (_ctx.modulator_level >> 1);
}

typedef synthFM_FM__ctx_type_0 synthFM_FM_setModulatorTargetLevel_type;

static_inline void synthFM_FM_setModulatorTargetLevel_init(synthFM_FM__ctx_type_0 &_output_){
   synthFM_FM__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_FM_setModulatorTargetLevel(synthFM_FM__ctx_type_0 &_ctx, uint8_t targetLevel){
   _ctx.modulator_target_level = targetLevel;
};

typedef synthFM_FM__ctx_type_0 synthFM_FM_setModulatorPhaseShift_type;

static_inline void synthFM_FM_setModulatorPhaseShift_init(synthFM_FM__ctx_type_0 &_output_){
   synthFM_FM__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_FM_setModulatorPhaseShift(synthFM_FM__ctx_type_0 &_ctx, fix16_t phaseRatio){
   phaseRatio = fix_clip(phaseRatio,0x0 /* 0.000000 */,0x10000 /* 1.000000 */);
   _ctx.modulator_phase_shift = fix_mul(phaseRatio,synthFM_OSC_getSize(_ctx.modulator));
   _ctx.modulator_phase_shift = (_ctx.modulator_phase_shift % synthFM_OSC_getSize(_ctx.modulator));
}

typedef synthFM_FM__ctx_type_0 synthFM_FM_setModulatorFeedback_type;

static_inline void synthFM_FM_setModulatorFeedback_init(synthFM_FM__ctx_type_0 &_output_){
   synthFM_FM__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_FM_setModulatorFeedback(synthFM_FM__ctx_type_0 &_ctx, fix16_t feedback){
   _ctx.modulator_feedback = feedback;
   _ctx.modulator_max_phase = (synthFM_OSC_getSize(_ctx.modulator) << 1);
   _ctx.modulator_phase_range = fix_mul(_ctx.modulator_max_phase,feedback);
}

typedef synthFM_FM__ctx_type_0 synthFM_FM_setFrequency_type;

static_inline void synthFM_FM_setFrequency_init(synthFM_FM__ctx_type_0 &_output_){
   synthFM_FM__ctx_type_0_init(_output_);
   return ;
}

void synthFM_FM_setFrequency(synthFM_FM__ctx_type_0 &_ctx, fix16_t newFreq);

typedef synthFM_FM__ctx_type_0 synthFM_FM_pitchBend_type;

static_inline void synthFM_FM_pitchBend_init(synthFM_FM__ctx_type_0 &_output_){
   synthFM_FM__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_FM_pitchBend(synthFM_FM__ctx_type_0 &_ctx, fix16_t semitones){
   if(semitones != _ctx.bend){
      _ctx.bend = semitones;
      synthFM_FM_setFrequency(_ctx,_ctx.freq);
   }
};

typedef synthFM_FM__ctx_type_0 synthFM_FM_setPoly_type;

static_inline void synthFM_FM_setPoly_init(synthFM_FM__ctx_type_0 &_output_){
   synthFM_FM__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_FM_setPoly(synthFM_FM__ctx_type_0 &_ctx, uint8_t flag){
   synthFM_Notes_setPoly(_ctx.playingnotes,flag);
};

typedef synthFM_FM__ctx_type_0 synthFM_FM_setSustain_type;

static_inline void synthFM_FM_setSustain_init(synthFM_FM__ctx_type_0 &_output_){
   synthFM_FM__ctx_type_0_init(_output_);
   return ;
}

void synthFM_FM_setSustain(synthFM_FM__ctx_type_0 &_ctx, uint8_t flag);

typedef synthFM_FM__ctx_type_0 synthFM_FM_noteOn_type;

static_inline void synthFM_FM_noteOn_init(synthFM_FM__ctx_type_0 &_output_){
   synthFM_FM__ctx_type_0_init(_output_);
   return ;
}

uint8_t synthFM_FM_noteOn(synthFM_FM__ctx_type_0 &_ctx, int note, int velocity, int channel);

typedef synthFM_FM__ctx_type_0 synthFM_FM_noteOff_type;

static_inline void synthFM_FM_noteOff_init(synthFM_FM__ctx_type_0 &_output_){
   synthFM_FM__ctx_type_0_init(_output_);
   return ;
}

void synthFM_FM_noteOff(synthFM_FM__ctx_type_0 &_ctx, int note, int channel);

typedef synthFM_FM__ctx_type_0 synthFM_FM_setModulatorADSR_type;

static_inline void synthFM_FM_setModulatorADSR_init(synthFM_FM__ctx_type_0 &_output_){
   synthFM_FM__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_FM_setModulatorADSR(synthFM_FM__ctx_type_0 &_ctx, fix16_t a, fix16_t d, fix16_t s, fix16_t r){
   synthFM_ADSR_config(_ctx.modulatoradsr,a,d,s,r);
};

typedef synthFM_FM__ctx_type_0 synthFM_FM_setCarrierADSR_type;

static_inline void synthFM_FM_setCarrierADSR_init(synthFM_FM__ctx_type_0 &_output_){
   synthFM_FM__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_FM_setCarrierADSR(synthFM_FM__ctx_type_0 &_ctx, fix16_t a, fix16_t d, fix16_t s, fix16_t r){
   synthFM_ADSR_config(_ctx.carrieradsr,a,d,s,r);
};

typedef synthFM_FM__ctx_type_0 synthFM_FM_default_type;

static_inline void synthFM_FM_default_init(synthFM_FM__ctx_type_0 &_output_){
   synthFM_FM__ctx_type_0_init(_output_);
   return ;
}

void synthFM_FM_default(synthFM_FM__ctx_type_0 &_ctx);

typedef struct synthFM_FM__ctx_type_1 {
   synthFM_FM__ctx_type_0 _inst115;
} synthFM_FM__ctx_type_1;

typedef synthFM_FM__ctx_type_1 synthFM_FM_dummy_type;

static_inline void synthFM_FM__ctx_type_1_init(synthFM_FM__ctx_type_1 &_output_){
   synthFM_FM__ctx_type_1 _ctx;
   synthFM_FM__ctx_type_0_init(_ctx._inst115);
   _output_ = _ctx;
   return ;
}

static_inline void synthFM_FM_dummy_init(synthFM_FM__ctx_type_1 &_output_){
   synthFM_FM__ctx_type_1_init(_output_);
   return ;
}

static_inline void synthFM_FM_dummy(synthFM_FM__ctx_type_1 &_ctx, fix16_t (&wavetable)[4096]){
   fix16_t buff[128];
   synthFM_Buffer_buffer(buff);
   synthFM_FM_process_bufferTo(_ctx._inst115,wavetable,wavetable,0,buff);
}

typedef struct synthFM_Poly__ctx_type_0 {
   fix16_t wavetable_modulator[4096];
   fix16_t wavetable_carrier[4096];
   synthFM_FM__ctx_type_0 voice3;
   synthFM_FM__ctx_type_0 voice2;
   synthFM_FM__ctx_type_0 voice1;
   synthFM_FM__ctx_type_0 voice0;
   uint8_t should_leftovers;
   fix16_t lastModulatorWavetablePhaseIdx;
   fix16_t lastModulatorWavetableIdx;
   fix16_t lastCarrierWavetablePhaseIdx;
   fix16_t lastCarrierWavetableIdx;
   uint8_t initModulatorWavetable;
   uint8_t initCarrierWavetable;
} synthFM_Poly__ctx_type_0;

typedef synthFM_Poly__ctx_type_0 synthFM_Poly_getSample_type;

void synthFM_Poly__ctx_type_0_init(synthFM_Poly__ctx_type_0 &_output_);

static_inline void synthFM_Poly_getSample_init(synthFM_Poly__ctx_type_0 &_output_){
   synthFM_Poly__ctx_type_0_init(_output_);
   return ;
}

fix16_t synthFM_Poly_getSample(synthFM_Poly__ctx_type_0 &_ctx, int voice);

typedef synthFM_Poly__ctx_type_0 synthFM_Poly_runVoice_type;

static_inline void synthFM_Poly_runVoice_init(synthFM_Poly__ctx_type_0 &_output_){
   synthFM_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Poly_runVoice(synthFM_Poly__ctx_type_0 &_ctx, int voice, int nb, fix16_t (&buff)[128]){
   switch(voice) {
      case 0:
         synthFM_FM_process_bufferTo(_ctx.voice0,_ctx.wavetable_modulator,_ctx.wavetable_carrier,nb,buff);
      break;
      case 1:
         synthFM_FM_process_bufferTo(_ctx.voice1,_ctx.wavetable_modulator,_ctx.wavetable_carrier,nb,buff);
      break;
      case 2:
         synthFM_FM_process_bufferTo(_ctx.voice2,_ctx.wavetable_modulator,_ctx.wavetable_carrier,nb,buff);
      break;
      case 3:
         synthFM_FM_process_bufferTo(_ctx.voice3,_ctx.wavetable_modulator,_ctx.wavetable_carrier,nb,buff);
      break;
    
   }
};

typedef synthFM_Poly__ctx_type_0 synthFM_Poly_sendNoteOn_type;

static_inline void synthFM_Poly_sendNoteOn_init(synthFM_Poly__ctx_type_0 &_output_){
   synthFM_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Poly_sendNoteOn(synthFM_Poly__ctx_type_0 &_ctx, int voice, int note, int velocity, int channel){
   switch(voice) {
      case 0:
         synthFM_FM_noteOn(_ctx.voice0,note,velocity,channel);
      break;
      case 1:
         synthFM_FM_noteOn(_ctx.voice1,note,velocity,channel);
      break;
      case 2:
         synthFM_FM_noteOn(_ctx.voice2,note,velocity,channel);
      break;
      case 3:
         synthFM_FM_noteOn(_ctx.voice3,note,velocity,channel);
      break;
    
   }
};

typedef synthFM_Poly__ctx_type_0 synthFM_Poly_sendNoteOff_type;

static_inline void synthFM_Poly_sendNoteOff_init(synthFM_Poly__ctx_type_0 &_output_){
   synthFM_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Poly_sendNoteOff(synthFM_Poly__ctx_type_0 &_ctx, int voice, int note, int channel){
   switch(voice) {
      case 0:
         synthFM_FM_noteOff(_ctx.voice0,note,channel);
      break;
      case 1:
         synthFM_FM_noteOff(_ctx.voice1,note,channel);
      break;
      case 2:
         synthFM_FM_noteOff(_ctx.voice2,note,channel);
      break;
      case 3:
         synthFM_FM_noteOff(_ctx.voice3,note,channel);
      break;
    
   }
};

typedef synthFM_Poly__ctx_type_0 synthFM_Poly_setSamplerate_type;

static_inline void synthFM_Poly_setSamplerate_init(synthFM_Poly__ctx_type_0 &_output_){
   synthFM_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Poly_setSamplerate(synthFM_Poly__ctx_type_0 &_ctx, fix16_t fs){
   synthFM_FM_setSamplerate(_ctx.voice0,fs);
   synthFM_FM_setSamplerate(_ctx.voice1,fs);
   synthFM_FM_setSamplerate(_ctx.voice2,fs);
   synthFM_FM_setSamplerate(_ctx.voice3,fs);
}

typedef synthFM_Poly__ctx_type_0 synthFM_Poly_synthSetSustain_type;

static_inline void synthFM_Poly_synthSetSustain_init(synthFM_Poly__ctx_type_0 &_output_){
   synthFM_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Poly_synthSetSustain(synthFM_Poly__ctx_type_0 &_ctx, uint8_t flag){
   synthFM_FM_setSustain(_ctx.voice0,flag);
   synthFM_FM_setSustain(_ctx.voice1,flag);
   synthFM_FM_setSustain(_ctx.voice2,flag);
   synthFM_FM_setSustain(_ctx.voice3,flag);
}

typedef synthFM_Poly__ctx_type_0 synthFM_Poly_synthPitchBend_type;

static_inline void synthFM_Poly_synthPitchBend_init(synthFM_Poly__ctx_type_0 &_output_){
   synthFM_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Poly_synthPitchBend(synthFM_Poly__ctx_type_0 &_ctx, fix16_t semitones){
   synthFM_FM_pitchBend(_ctx.voice0,semitones);
   synthFM_FM_pitchBend(_ctx.voice1,semitones);
   synthFM_FM_pitchBend(_ctx.voice2,semitones);
   synthFM_FM_pitchBend(_ctx.voice3,semitones);
}

typedef synthFM_Poly__ctx_type_0 synthFM_Poly_synthSetLoop_type;

static_inline void synthFM_Poly_synthSetLoop_init(synthFM_Poly__ctx_type_0 &_output_){
   synthFM_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Poly_synthSetLoop(synthFM_Poly__ctx_type_0 &_ctx, uint8_t flag){
}

typedef synthFM_Poly__ctx_type_0 synthFM_Poly_synthSetLoopStart_type;

static_inline void synthFM_Poly_synthSetLoopStart_init(synthFM_Poly__ctx_type_0 &_output_){
   synthFM_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Poly_synthSetLoopStart(synthFM_Poly__ctx_type_0 &_ctx, int value){
}

typedef synthFM_Poly__ctx_type_0 synthFM_Poly_synthSetLoopEnd_type;

static_inline void synthFM_Poly_synthSetLoopEnd_init(synthFM_Poly__ctx_type_0 &_output_){
   synthFM_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Poly_synthSetLoopEnd(synthFM_Poly__ctx_type_0 &_ctx, int value){
}

typedef synthFM_Poly__ctx_type_0 synthFM_Poly_synthGetLoop_type;

static_inline void synthFM_Poly_synthGetLoop_init(synthFM_Poly__ctx_type_0 &_output_){
   synthFM_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline uint8_t synthFM_Poly_synthGetLoop(synthFM_Poly__ctx_type_0 &_ctx){
   return false;
};

typedef synthFM_Poly__ctx_type_0 synthFM_Poly_synthGetLoopStart_type;

static_inline void synthFM_Poly_synthGetLoopStart_init(synthFM_Poly__ctx_type_0 &_output_){
   synthFM_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline int synthFM_Poly_synthGetLoopStart(synthFM_Poly__ctx_type_0 &_ctx){
   return 0;
};

typedef synthFM_Poly__ctx_type_0 synthFM_Poly_synthGetLoopEnd_type;

static_inline void synthFM_Poly_synthGetLoopEnd_init(synthFM_Poly__ctx_type_0 &_output_){
   synthFM_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline int synthFM_Poly_synthGetLoopEnd(synthFM_Poly__ctx_type_0 &_ctx){
   return 0;
};

typedef synthFM_Poly__ctx_type_0 synthFM_Poly_synthGetSize_type;

static_inline void synthFM_Poly_synthGetSize_init(synthFM_Poly__ctx_type_0 &_output_){
   synthFM_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline int synthFM_Poly_synthGetSize(synthFM_Poly__ctx_type_0 &_ctx){
   return 0;
};

typedef synthFM_Poly__ctx_type_0 synthFM_Poly_synthGetNbWavetables_type;

static_inline void synthFM_Poly_synthGetNbWavetables_init(synthFM_Poly__ctx_type_0 &_output_){
   synthFM_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline int synthFM_Poly_synthGetNbWavetables(synthFM_Poly__ctx_type_0 &_ctx){
   return 8;
};

typedef synthFM_Poly__ctx_type_0 synthFM_Poly_synthSetModulatorWavetable_type;

static_inline void synthFM_Poly_synthSetModulatorWavetable_init(synthFM_Poly__ctx_type_0 &_output_){
   synthFM_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Poly_synthSetModulatorWavetable(synthFM_Poly__ctx_type_0 &_ctx, fix16_t wavetableIdx){
   if(bool_not(_ctx.initModulatorWavetable) || (wavetableIdx != _ctx.lastModulatorWavetableIdx)){
      synthFM_Wavetable_morphTo(wavetableIdx,_ctx.lastModulatorWavetablePhaseIdx,_ctx.wavetable_modulator);
      _ctx.lastModulatorWavetableIdx = wavetableIdx;
      _ctx.initModulatorWavetable = true;
   }
};

typedef synthFM_Poly__ctx_type_0 synthFM_Poly_synthSetModulatorWavetablePhase_type;

static_inline void synthFM_Poly_synthSetModulatorWavetablePhase_init(synthFM_Poly__ctx_type_0 &_output_){
   synthFM_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Poly_synthSetModulatorWavetablePhase(synthFM_Poly__ctx_type_0 &_ctx, fix16_t phaseIdx){
   if(phaseIdx != _ctx.lastModulatorWavetablePhaseIdx){
      synthFM_Wavetable_morphTo(_ctx.lastModulatorWavetableIdx,phaseIdx,_ctx.wavetable_modulator);
      _ctx.lastModulatorWavetablePhaseIdx = phaseIdx;
   }
};

typedef synthFM_Poly__ctx_type_0 synthFM_Poly_synthSetCarrierWavetable_type;

static_inline void synthFM_Poly_synthSetCarrierWavetable_init(synthFM_Poly__ctx_type_0 &_output_){
   synthFM_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Poly_synthSetCarrierWavetable(synthFM_Poly__ctx_type_0 &_ctx, fix16_t wavetableIdx){
   if(bool_not(_ctx.initCarrierWavetable) || (wavetableIdx != _ctx.lastCarrierWavetableIdx)){
      synthFM_Wavetable_morphTo(wavetableIdx,_ctx.lastCarrierWavetablePhaseIdx,_ctx.wavetable_carrier);
      _ctx.lastCarrierWavetableIdx = wavetableIdx;
      _ctx.initCarrierWavetable = true;
   }
};

typedef synthFM_Poly__ctx_type_0 synthFM_Poly_synthSetCarrierWavetablePhase_type;

static_inline void synthFM_Poly_synthSetCarrierWavetablePhase_init(synthFM_Poly__ctx_type_0 &_output_){
   synthFM_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Poly_synthSetCarrierWavetablePhase(synthFM_Poly__ctx_type_0 &_ctx, fix16_t phaseIdx){
   if(phaseIdx != _ctx.lastCarrierWavetablePhaseIdx){
      synthFM_Wavetable_morphTo(_ctx.lastCarrierWavetableIdx,phaseIdx,_ctx.wavetable_carrier);
      _ctx.lastCarrierWavetablePhaseIdx = phaseIdx;
   }
};

typedef synthFM_Poly__ctx_type_0 synthFM_Poly_synthSetModulatorRatio_type;

static_inline void synthFM_Poly_synthSetModulatorRatio_init(synthFM_Poly__ctx_type_0 &_output_){
   synthFM_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Poly_synthSetModulatorRatio(synthFM_Poly__ctx_type_0 &_ctx, fix16_t ratio){
   synthFM_FM_setModulatorRatio(_ctx.voice0,ratio);
   synthFM_FM_setModulatorRatio(_ctx.voice1,ratio);
   synthFM_FM_setModulatorRatio(_ctx.voice2,ratio);
   synthFM_FM_setModulatorRatio(_ctx.voice3,ratio);
}

typedef synthFM_Poly__ctx_type_0 synthFM_Poly_synthSetCarrierRatio_type;

static_inline void synthFM_Poly_synthSetCarrierRatio_init(synthFM_Poly__ctx_type_0 &_output_){
   synthFM_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Poly_synthSetCarrierRatio(synthFM_Poly__ctx_type_0 &_ctx, fix16_t ratio){
   synthFM_FM_setCarrierRatio(_ctx.voice0,ratio);
   synthFM_FM_setCarrierRatio(_ctx.voice1,ratio);
   synthFM_FM_setCarrierRatio(_ctx.voice2,ratio);
   synthFM_FM_setCarrierRatio(_ctx.voice3,ratio);
}

typedef synthFM_Poly__ctx_type_0 synthFM_Poly_synthSetModulatorLevel_type;

static_inline void synthFM_Poly_synthSetModulatorLevel_init(synthFM_Poly__ctx_type_0 &_output_){
   synthFM_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Poly_synthSetModulatorLevel(synthFM_Poly__ctx_type_0 &_ctx, fix16_t level){
   synthFM_FM_setModulatorLevel(_ctx.voice0,level);
   synthFM_FM_setModulatorLevel(_ctx.voice1,level);
   synthFM_FM_setModulatorLevel(_ctx.voice2,level);
   synthFM_FM_setModulatorLevel(_ctx.voice3,level);
}

typedef synthFM_Poly__ctx_type_0 synthFM_Poly_synthSetModulatorTargetLevel_type;

static_inline void synthFM_Poly_synthSetModulatorTargetLevel_init(synthFM_Poly__ctx_type_0 &_output_){
   synthFM_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Poly_synthSetModulatorTargetLevel(synthFM_Poly__ctx_type_0 &_ctx, uint8_t targetLevel){
   synthFM_FM_setModulatorTargetLevel(_ctx.voice0,targetLevel);
   synthFM_FM_setModulatorTargetLevel(_ctx.voice1,targetLevel);
   synthFM_FM_setModulatorTargetLevel(_ctx.voice2,targetLevel);
   synthFM_FM_setModulatorTargetLevel(_ctx.voice3,targetLevel);
}

typedef synthFM_Poly__ctx_type_0 synthFM_Poly_synthSetModulatorPhaseShift_type;

static_inline void synthFM_Poly_synthSetModulatorPhaseShift_init(synthFM_Poly__ctx_type_0 &_output_){
   synthFM_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Poly_synthSetModulatorPhaseShift(synthFM_Poly__ctx_type_0 &_ctx, fix16_t ratio){
   synthFM_FM_setModulatorPhaseShift(_ctx.voice0,ratio);
   synthFM_FM_setModulatorPhaseShift(_ctx.voice1,ratio);
   synthFM_FM_setModulatorPhaseShift(_ctx.voice2,ratio);
   synthFM_FM_setModulatorPhaseShift(_ctx.voice3,ratio);
}

typedef synthFM_Poly__ctx_type_0 synthFM_Poly_synthSetModulatorFeedback_type;

static_inline void synthFM_Poly_synthSetModulatorFeedback_init(synthFM_Poly__ctx_type_0 &_output_){
   synthFM_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Poly_synthSetModulatorFeedback(synthFM_Poly__ctx_type_0 &_ctx, fix16_t ratio){
   synthFM_FM_setModulatorFeedback(_ctx.voice0,ratio);
   synthFM_FM_setModulatorFeedback(_ctx.voice1,ratio);
   synthFM_FM_setModulatorFeedback(_ctx.voice2,ratio);
   synthFM_FM_setModulatorFeedback(_ctx.voice3,ratio);
}

typedef synthFM_Poly__ctx_type_0 synthFM_Poly_synthSetModulatorADSR_type;

static_inline void synthFM_Poly_synthSetModulatorADSR_init(synthFM_Poly__ctx_type_0 &_output_){
   synthFM_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Poly_synthSetModulatorADSR(synthFM_Poly__ctx_type_0 &_ctx, fix16_t a, fix16_t d, fix16_t s, fix16_t r){
   synthFM_FM_setModulatorADSR(_ctx.voice0,a,d,s,r);
   synthFM_FM_setModulatorADSR(_ctx.voice1,a,d,s,r);
   synthFM_FM_setModulatorADSR(_ctx.voice2,a,d,s,r);
   synthFM_FM_setModulatorADSR(_ctx.voice3,a,d,s,r);
}

typedef synthFM_Poly__ctx_type_0 synthFM_Poly_synthSetCarrierADSR_type;

static_inline void synthFM_Poly_synthSetCarrierADSR_init(synthFM_Poly__ctx_type_0 &_output_){
   synthFM_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Poly_synthSetCarrierADSR(synthFM_Poly__ctx_type_0 &_ctx, fix16_t a, fix16_t d, fix16_t s, fix16_t r){
   synthFM_FM_setCarrierADSR(_ctx.voice0,a,d,s,r);
   synthFM_FM_setCarrierADSR(_ctx.voice1,a,d,s,r);
   synthFM_FM_setCarrierADSR(_ctx.voice2,a,d,s,r);
   synthFM_FM_setCarrierADSR(_ctx.voice3,a,d,s,r);
}

typedef synthFM_Poly__ctx_type_0 synthFM_Poly_shouldLeftOvers_type;

static_inline void synthFM_Poly_shouldLeftOvers_init(synthFM_Poly__ctx_type_0 &_output_){
   synthFM_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline uint8_t synthFM_Poly_shouldLeftOvers(synthFM_Poly__ctx_type_0 &_ctx){
   return _ctx.should_leftovers;
};

typedef synthFM_Poly__ctx_type_0 synthFM_Poly_default_type;

static_inline void synthFM_Poly_default_init(synthFM_Poly__ctx_type_0 &_output_){
   synthFM_Poly__ctx_type_0_init(_output_);
   return ;
}

void synthFM_Poly_default(synthFM_Poly__ctx_type_0 &_ctx);

typedef struct synthFM_Poly__ctx_type_1 {
   synthFM_Poly__ctx_type_0 _inst179;
} synthFM_Poly__ctx_type_1;

typedef synthFM_Poly__ctx_type_1 synthFM_Poly_dummy_type;

static_inline void synthFM_Poly__ctx_type_1_init(synthFM_Poly__ctx_type_1 &_output_){
   synthFM_Poly__ctx_type_1 _ctx;
   synthFM_Poly__ctx_type_0_init(_ctx._inst179);
   _output_ = _ctx;
   return ;
}

static_inline void synthFM_Poly_dummy_init(synthFM_Poly__ctx_type_1 &_output_){
   synthFM_Poly__ctx_type_1_init(_output_);
   return ;
}

static_inline void synthFM_Poly_dummy(synthFM_Poly__ctx_type_1 &_ctx){
   fix16_t buff[128];
   synthFM_Buffer_buffer(buff);
   synthFM_Poly_runVoice(_ctx._inst179,0,0,buff);
}

typedef struct synthFM_Voice__ctx_type_0 {
   synthFM_Notes__ctx_type_0 voicesinactive;
   synthFM_Notes__ctx_type_0 voicesactive;
   fix16_t voices_ratio;
   int voices[4];
   synthFM_Notes__ctx_type_0 voiceinsactive;
   uint8_t reuse;
   synthFM_Poly__ctx_type_0 poly;
   int number_voices;
   int notes[128];
   uint8_t normalize;
   fix16_t leftovers_decay;
   fix16_t leftovers;
   int last_velocities[4];
   fix16_t last_values[4];
   fix16_t fs;
   fix16_t buffer_v0[128];
} synthFM_Voice__ctx_type_0;

typedef synthFM_Voice__ctx_type_0 synthFM_Voice_process_type;

void synthFM_Voice__ctx_type_0_init(synthFM_Voice__ctx_type_0 &_output_);

static_inline void synthFM_Voice_process_init(synthFM_Voice__ctx_type_0 &_output_){
   synthFM_Voice__ctx_type_0_init(_output_);
   return ;
}

fix16_t synthFM_Voice_process(synthFM_Voice__ctx_type_0 &_ctx);

typedef synthFM_Voice__ctx_type_0 synthFM_Voice_process_bufferTo_type;

static_inline void synthFM_Voice_process_bufferTo_init(synthFM_Voice__ctx_type_0 &_output_){
   synthFM_Voice__ctx_type_0_init(_output_);
   return ;
}

void synthFM_Voice_process_bufferTo(synthFM_Voice__ctx_type_0 &_ctx, int nb, fix16_t (&oBuffer)[128]);

typedef synthFM_Voice__ctx_type_0 synthFM_Voice_setReuse_type;

static_inline void synthFM_Voice_setReuse_init(synthFM_Voice__ctx_type_0 &_output_){
   synthFM_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Voice_setReuse(synthFM_Voice__ctx_type_0 &_ctx, uint8_t flag){
   _ctx.reuse = flag;
};

typedef synthFM_Voice__ctx_type_0 synthFM_Voice_noteOff_type;

static_inline void synthFM_Voice_noteOff_init(synthFM_Voice__ctx_type_0 &_output_){
   synthFM_Voice__ctx_type_0_init(_output_);
   return ;
}

void synthFM_Voice_noteOff(synthFM_Voice__ctx_type_0 &_ctx, int note, int channel);

typedef synthFM_Voice__ctx_type_0 synthFM_Voice_noteOn_type;

static_inline void synthFM_Voice_noteOn_init(synthFM_Voice__ctx_type_0 &_output_){
   synthFM_Voice__ctx_type_0_init(_output_);
   return ;
}

void synthFM_Voice_noteOn(synthFM_Voice__ctx_type_0 &_ctx, int note, int velocity, int channel);

typedef synthFM_Voice__ctx_type_0 synthFM_Voice_setNbVoices_type;

static_inline void synthFM_Voice_setNbVoices_init(synthFM_Voice__ctx_type_0 &_output_){
   synthFM_Voice__ctx_type_0_init(_output_);
   return ;
}

void synthFM_Voice_setNbVoices(synthFM_Voice__ctx_type_0 &_ctx, int nbvoices);

typedef synthFM_Voice__ctx_type_0 synthFM_Voice_setNormalize_type;

static_inline void synthFM_Voice_setNormalize_init(synthFM_Voice__ctx_type_0 &_output_){
   synthFM_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Voice_setNormalize(synthFM_Voice__ctx_type_0 &_ctx, uint8_t flag){
   _ctx.normalize = flag;
};

typedef synthFM_Voice__ctx_type_0 synthFM_Voice_setSamplerate_type;

static_inline void synthFM_Voice_setSamplerate_init(synthFM_Voice__ctx_type_0 &_output_){
   synthFM_Voice__ctx_type_0_init(_output_);
   return ;
}

void synthFM_Voice_setSamplerate(synthFM_Voice__ctx_type_0 &_ctx, fix16_t newFs);

typedef synthFM_Voice__ctx_type_0 synthFM_Voice_synthSetSustain_type;

static_inline void synthFM_Voice_synthSetSustain_init(synthFM_Voice__ctx_type_0 &_output_){
   synthFM_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Voice_synthSetSustain(synthFM_Voice__ctx_type_0 &_ctx, uint8_t flag){
   synthFM_Poly_synthSetSustain(_ctx.poly,flag);
};

typedef synthFM_Voice__ctx_type_0 synthFM_Voice_synthPitchBend_type;

static_inline void synthFM_Voice_synthPitchBend_init(synthFM_Voice__ctx_type_0 &_output_){
   synthFM_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Voice_synthPitchBend(synthFM_Voice__ctx_type_0 &_ctx, fix16_t semitones){
   synthFM_Poly_synthPitchBend(_ctx.poly,semitones);
};

typedef synthFM_Voice__ctx_type_0 synthFM_Voice_synthSetLoop_type;

static_inline void synthFM_Voice_synthSetLoop_init(synthFM_Voice__ctx_type_0 &_output_){
   synthFM_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Voice_synthSetLoop(synthFM_Voice__ctx_type_0 &_ctx, uint8_t flag){
   synthFM_Poly_synthSetLoop(_ctx.poly,flag);
};

typedef synthFM_Voice__ctx_type_0 synthFM_Voice_synthSetLoopStart_type;

static_inline void synthFM_Voice_synthSetLoopStart_init(synthFM_Voice__ctx_type_0 &_output_){
   synthFM_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Voice_synthSetLoopStart(synthFM_Voice__ctx_type_0 &_ctx, int value){
   synthFM_Poly_synthSetLoopStart(_ctx.poly,value);
};

typedef synthFM_Voice__ctx_type_0 synthFM_Voice_synthSetLoopEnd_type;

static_inline void synthFM_Voice_synthSetLoopEnd_init(synthFM_Voice__ctx_type_0 &_output_){
   synthFM_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Voice_synthSetLoopEnd(synthFM_Voice__ctx_type_0 &_ctx, int value){
   synthFM_Poly_synthSetLoopEnd(_ctx.poly,value);
};

typedef synthFM_Voice__ctx_type_0 synthFM_Voice_synthGetLoop_type;

static_inline void synthFM_Voice_synthGetLoop_init(synthFM_Voice__ctx_type_0 &_output_){
   synthFM_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline uint8_t synthFM_Voice_synthGetLoop(synthFM_Voice__ctx_type_0 &_ctx){
   return synthFM_Poly_synthGetLoop(_ctx.poly);
};

typedef synthFM_Voice__ctx_type_0 synthFM_Voice_synthGetLoopStart_type;

static_inline void synthFM_Voice_synthGetLoopStart_init(synthFM_Voice__ctx_type_0 &_output_){
   synthFM_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline int synthFM_Voice_synthGetLoopStart(synthFM_Voice__ctx_type_0 &_ctx){
   return synthFM_Poly_synthGetLoopStart(_ctx.poly);
};

typedef synthFM_Voice__ctx_type_0 synthFM_Voice_synthGetLoopEnd_type;

static_inline void synthFM_Voice_synthGetLoopEnd_init(synthFM_Voice__ctx_type_0 &_output_){
   synthFM_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline int synthFM_Voice_synthGetLoopEnd(synthFM_Voice__ctx_type_0 &_ctx){
   return synthFM_Poly_synthGetLoopEnd(_ctx.poly);
};

typedef synthFM_Voice__ctx_type_0 synthFM_Voice_synthGetSize_type;

static_inline void synthFM_Voice_synthGetSize_init(synthFM_Voice__ctx_type_0 &_output_){
   synthFM_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline int synthFM_Voice_synthGetSize(synthFM_Voice__ctx_type_0 &_ctx){
   return synthFM_Poly_synthGetSize(_ctx.poly);
};

typedef synthFM_Voice__ctx_type_0 synthFM_Voice_synthGetNbWavetables_type;

static_inline void synthFM_Voice_synthGetNbWavetables_init(synthFM_Voice__ctx_type_0 &_output_){
   synthFM_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline int synthFM_Voice_synthGetNbWavetables(synthFM_Voice__ctx_type_0 &_ctx){
   return synthFM_Poly_synthGetNbWavetables(_ctx.poly);
};

typedef synthFM_Voice__ctx_type_0 synthFM_Voice_synthSetModulatorWavetable_type;

static_inline void synthFM_Voice_synthSetModulatorWavetable_init(synthFM_Voice__ctx_type_0 &_output_){
   synthFM_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Voice_synthSetModulatorWavetable(synthFM_Voice__ctx_type_0 &_ctx, fix16_t wavetableIdx){
   synthFM_Poly_synthSetModulatorWavetable(_ctx.poly,wavetableIdx);
};

typedef synthFM_Voice__ctx_type_0 synthFM_Voice_synthSetModulatorWavetablePhase_type;

static_inline void synthFM_Voice_synthSetModulatorWavetablePhase_init(synthFM_Voice__ctx_type_0 &_output_){
   synthFM_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Voice_synthSetModulatorWavetablePhase(synthFM_Voice__ctx_type_0 &_ctx, fix16_t phaseIdx){
   synthFM_Poly_synthSetModulatorWavetablePhase(_ctx.poly,phaseIdx);
};

typedef synthFM_Voice__ctx_type_0 synthFM_Voice_synthSetCarrierWavetable_type;

static_inline void synthFM_Voice_synthSetCarrierWavetable_init(synthFM_Voice__ctx_type_0 &_output_){
   synthFM_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Voice_synthSetCarrierWavetable(synthFM_Voice__ctx_type_0 &_ctx, fix16_t wavetableIdx){
   synthFM_Poly_synthSetCarrierWavetable(_ctx.poly,wavetableIdx);
};

typedef synthFM_Voice__ctx_type_0 synthFM_Voice_synthSetCarrierWavetablePhase_type;

static_inline void synthFM_Voice_synthSetCarrierWavetablePhase_init(synthFM_Voice__ctx_type_0 &_output_){
   synthFM_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Voice_synthSetCarrierWavetablePhase(synthFM_Voice__ctx_type_0 &_ctx, fix16_t phaseIdx){
   synthFM_Poly_synthSetCarrierWavetablePhase(_ctx.poly,phaseIdx);
};

typedef synthFM_Voice__ctx_type_0 synthFM_Voice_synthSetModulatorRatio_type;

static_inline void synthFM_Voice_synthSetModulatorRatio_init(synthFM_Voice__ctx_type_0 &_output_){
   synthFM_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Voice_synthSetModulatorRatio(synthFM_Voice__ctx_type_0 &_ctx, fix16_t ratio){
   synthFM_Poly_synthSetModulatorRatio(_ctx.poly,ratio);
};

typedef synthFM_Voice__ctx_type_0 synthFM_Voice_synthSetCarrierRatio_type;

static_inline void synthFM_Voice_synthSetCarrierRatio_init(synthFM_Voice__ctx_type_0 &_output_){
   synthFM_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Voice_synthSetCarrierRatio(synthFM_Voice__ctx_type_0 &_ctx, fix16_t ratio){
   synthFM_Poly_synthSetCarrierRatio(_ctx.poly,ratio);
};

typedef synthFM_Voice__ctx_type_0 synthFM_Voice_synthSetModulatorLevel_type;

static_inline void synthFM_Voice_synthSetModulatorLevel_init(synthFM_Voice__ctx_type_0 &_output_){
   synthFM_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Voice_synthSetModulatorLevel(synthFM_Voice__ctx_type_0 &_ctx, fix16_t level){
   synthFM_Poly_synthSetModulatorLevel(_ctx.poly,level);
};

typedef synthFM_Voice__ctx_type_0 synthFM_Voice_synthSetModulatorTargetLevel_type;

static_inline void synthFM_Voice_synthSetModulatorTargetLevel_init(synthFM_Voice__ctx_type_0 &_output_){
   synthFM_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Voice_synthSetModulatorTargetLevel(synthFM_Voice__ctx_type_0 &_ctx, uint8_t targetLevel){
   synthFM_Poly_synthSetModulatorTargetLevel(_ctx.poly,targetLevel);
};

typedef synthFM_Voice__ctx_type_0 synthFM_Voice_synthSetModulatorPhaseShift_type;

static_inline void synthFM_Voice_synthSetModulatorPhaseShift_init(synthFM_Voice__ctx_type_0 &_output_){
   synthFM_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Voice_synthSetModulatorPhaseShift(synthFM_Voice__ctx_type_0 &_ctx, fix16_t ratio){
   synthFM_Poly_synthSetModulatorPhaseShift(_ctx.poly,ratio);
};

typedef synthFM_Voice__ctx_type_0 synthFM_Voice_synthSetModulatorFeedback_type;

static_inline void synthFM_Voice_synthSetModulatorFeedback_init(synthFM_Voice__ctx_type_0 &_output_){
   synthFM_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Voice_synthSetModulatorFeedback(synthFM_Voice__ctx_type_0 &_ctx, fix16_t ratio){
   synthFM_Poly_synthSetModulatorFeedback(_ctx.poly,ratio);
};

typedef synthFM_Voice__ctx_type_0 synthFM_Voice_synthSetModulatorADSR_type;

static_inline void synthFM_Voice_synthSetModulatorADSR_init(synthFM_Voice__ctx_type_0 &_output_){
   synthFM_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Voice_synthSetModulatorADSR(synthFM_Voice__ctx_type_0 &_ctx, fix16_t a, fix16_t d, fix16_t s, fix16_t r){
   synthFM_Poly_synthSetModulatorADSR(_ctx.poly,a,d,s,r);
};

typedef synthFM_Voice__ctx_type_0 synthFM_Voice_synthSetCarrierADSR_type;

static_inline void synthFM_Voice_synthSetCarrierADSR_init(synthFM_Voice__ctx_type_0 &_output_){
   synthFM_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthFM_Voice_synthSetCarrierADSR(synthFM_Voice__ctx_type_0 &_ctx, fix16_t a, fix16_t d, fix16_t s, fix16_t r){
   synthFM_Poly_synthSetCarrierADSR(_ctx.poly,a,d,s,r);
};

typedef synthFM_Voice__ctx_type_0 synthFM_Voice_default_type;

static_inline void synthFM_Voice_default_init(synthFM_Voice__ctx_type_0 &_output_){
   synthFM_Voice__ctx_type_0_init(_output_);
   return ;
}

void synthFM_Voice_default(synthFM_Voice__ctx_type_0 &_ctx);

typedef struct synthFM_Voice__ctx_type_1 {
   synthFM_Voice__ctx_type_0 _inst1b9;
} synthFM_Voice__ctx_type_1;

typedef synthFM_Voice__ctx_type_1 synthFM_Voice_dummy_type;

static_inline void synthFM_Voice__ctx_type_1_init(synthFM_Voice__ctx_type_1 &_output_){
   synthFM_Voice__ctx_type_1 _ctx;
   synthFM_Voice__ctx_type_0_init(_ctx._inst1b9);
   _output_ = _ctx;
   return ;
}

static_inline void synthFM_Voice_dummy_init(synthFM_Voice__ctx_type_1 &_output_){
   synthFM_Voice__ctx_type_1_init(_output_);
   return ;
}

static_inline void synthFM_Voice_dummy(synthFM_Voice__ctx_type_1 &_ctx){
   fix16_t buff[128];
   synthFM_Buffer_buffer(buff);
   synthFM_Voice_process_bufferTo(_ctx._inst1b9,0,buff);
}

typedef struct synthFM_Processor__ctx_type_0 {
   fix16_t pre_d;
   fix16_t pre_c;
   fix16_t pre_b;
   fix16_t pre_a;
} synthFM_Processor__ctx_type_0;

typedef synthFM_Processor__ctx_type_0 synthFM_Processor_change4_type;

void synthFM_Processor__ctx_type_0_init(synthFM_Processor__ctx_type_0 &_output_);

static_inline void synthFM_Processor_change4_init(synthFM_Processor__ctx_type_0 &_output_){
   synthFM_Processor__ctx_type_0_init(_output_);
   return ;
}

uint8_t synthFM_Processor_change4(synthFM_Processor__ctx_type_0 &_ctx, fix16_t a, fix16_t b, fix16_t c, fix16_t d);

int synthFM_Processor_cvToPitch(fix16_t cv);

typedef struct synthFM_Processor__ctx_type_2 {
   synthFM_Voice__ctx_type_0 voice;
   uint8_t last_retrigger[16];
   int last_pitches[16];
   int last_nbcables;
   uint8_t last_gates[16];
   fix16_t fs;
   synthFM_Processor__ctx_type_0 _inst5336;
   synthFM_Processor__ctx_type_0 _inst5036;
   synthFM_Util__ctx_type_4 _inst473b;
   synthFM_Util__ctx_type_4 _inst443b;
   synthFM_Util__ctx_type_4 _inst393b;
   synthFM_Util__ctx_type_4 _inst363b;
   synthFM_Util__ctx_type_4 _inst333b;
   synthFM_Util__ctx_type_4 _inst303b;
   synthFM_Util__ctx_type_4 _inst273b;
   synthFM_Util__ctx_type_4 _inst243b;
   synthFM_Util__ctx_type_4 _inst213b;
   synthFM_Util__ctx_type_4 _inst183b;
} synthFM_Processor__ctx_type_2;

typedef synthFM_Processor__ctx_type_2 synthFM_Processor_process_type;

void synthFM_Processor__ctx_type_2_init(synthFM_Processor__ctx_type_2 &_output_);

static_inline void synthFM_Processor_process_init(synthFM_Processor__ctx_type_2 &_output_){
   synthFM_Processor__ctx_type_2_init(_output_);
   return ;
}

static_inline fix16_t synthFM_Processor_process(synthFM_Processor__ctx_type_2 &_ctx){
   return synthFM_Voice_process(_ctx.voice);
};

typedef synthFM_Processor__ctx_type_2 synthFM_Processor_setNote_type;

static_inline void synthFM_Processor_setNote_init(synthFM_Processor__ctx_type_2 &_output_){
   synthFM_Processor__ctx_type_2_init(_output_);
   return ;
}

void synthFM_Processor_setNote(synthFM_Processor__ctx_type_2 &_ctx, fix16_t gate, fix16_t voct, fix16_t vel, fix16_t retrigger, int cable);

typedef synthFM_Processor__ctx_type_2 synthFM_Processor_setPitchBend_type;

static_inline void synthFM_Processor_setPitchBend_init(synthFM_Processor__ctx_type_2 &_output_){
   synthFM_Processor__ctx_type_2_init(_output_);
   return ;
}

static_inline void synthFM_Processor_setPitchBend(synthFM_Processor__ctx_type_2 &_ctx, fix16_t semitones){
   synthFM_Voice_synthPitchBend(_ctx.voice,semitones);
};

typedef synthFM_Processor__ctx_type_2 synthFM_Processor_nbCables_type;

static_inline void synthFM_Processor_nbCables_init(synthFM_Processor__ctx_type_2 &_output_){
   synthFM_Processor__ctx_type_2_init(_output_);
   return ;
}

void synthFM_Processor_nbCables(synthFM_Processor__ctx_type_2 &_ctx, int nbcables);

typedef synthFM_Processor__ctx_type_2 synthFM_Processor_setSamplerate_type;

static_inline void synthFM_Processor_setSamplerate_init(synthFM_Processor__ctx_type_2 &_output_){
   synthFM_Processor__ctx_type_2_init(_output_);
   return ;
}

static_inline void synthFM_Processor_setSamplerate(synthFM_Processor__ctx_type_2 &_ctx, fix16_t newFs){
   if((newFs > 0x0 /* 0.000000 */) && (newFs != _ctx.fs)){
      _ctx.fs = newFs;
      synthFM_Voice_setSamplerate(_ctx.voice,_ctx.fs);
   }
};

typedef synthFM_Processor__ctx_type_2 synthFM_Processor_setModulatorWavetable_type;

static_inline void synthFM_Processor_setModulatorWavetable_init(synthFM_Processor__ctx_type_2 &_output_){
   synthFM_Processor__ctx_type_2_init(_output_);
   return ;
}

static_inline void synthFM_Processor_setModulatorWavetable(synthFM_Processor__ctx_type_2 &_ctx, fix16_t wavetableIdx, uint8_t force){
   if(synthFM_Util_change(_ctx._inst183b,wavetableIdx) || force){
      synthFM_Voice_synthSetModulatorWavetable(_ctx.voice,wavetableIdx);
   }
};

typedef synthFM_Processor__ctx_type_2 synthFM_Processor_setModulatorWavetablePhase_type;

static_inline void synthFM_Processor_setModulatorWavetablePhase_init(synthFM_Processor__ctx_type_2 &_output_){
   synthFM_Processor__ctx_type_2_init(_output_);
   return ;
}

static_inline void synthFM_Processor_setModulatorWavetablePhase(synthFM_Processor__ctx_type_2 &_ctx, fix16_t phaseIdx, uint8_t force){
   if(synthFM_Util_change(_ctx._inst213b,phaseIdx) || force){
      synthFM_Voice_synthSetModulatorWavetablePhase(_ctx.voice,phaseIdx);
   }
};

typedef synthFM_Processor__ctx_type_2 synthFM_Processor_setCarrierWavetable_type;

static_inline void synthFM_Processor_setCarrierWavetable_init(synthFM_Processor__ctx_type_2 &_output_){
   synthFM_Processor__ctx_type_2_init(_output_);
   return ;
}

static_inline void synthFM_Processor_setCarrierWavetable(synthFM_Processor__ctx_type_2 &_ctx, fix16_t wavetableIdx, uint8_t force){
   if(synthFM_Util_change(_ctx._inst243b,wavetableIdx) || force){
      synthFM_Voice_synthSetCarrierWavetable(_ctx.voice,wavetableIdx);
   }
};

typedef synthFM_Processor__ctx_type_2 synthFM_Processor_setCarrierWavetablePhase_type;

static_inline void synthFM_Processor_setCarrierWavetablePhase_init(synthFM_Processor__ctx_type_2 &_output_){
   synthFM_Processor__ctx_type_2_init(_output_);
   return ;
}

static_inline void synthFM_Processor_setCarrierWavetablePhase(synthFM_Processor__ctx_type_2 &_ctx, fix16_t phaseIdx, uint8_t force){
   if(synthFM_Util_change(_ctx._inst273b,phaseIdx) || force){
      synthFM_Voice_synthSetCarrierWavetablePhase(_ctx.voice,phaseIdx);
   }
};

typedef synthFM_Processor__ctx_type_2 synthFM_Processor_setModulatorRatio_type;

static_inline void synthFM_Processor_setModulatorRatio_init(synthFM_Processor__ctx_type_2 &_output_){
   synthFM_Processor__ctx_type_2_init(_output_);
   return ;
}

static_inline void synthFM_Processor_setModulatorRatio(synthFM_Processor__ctx_type_2 &_ctx, fix16_t ratio, uint8_t force){
   if(synthFM_Util_change(_ctx._inst303b,ratio) || force){
      synthFM_Voice_synthSetModulatorRatio(_ctx.voice,ratio);
   }
};

typedef synthFM_Processor__ctx_type_2 synthFM_Processor_setCarrierRatio_type;

static_inline void synthFM_Processor_setCarrierRatio_init(synthFM_Processor__ctx_type_2 &_output_){
   synthFM_Processor__ctx_type_2_init(_output_);
   return ;
}

static_inline void synthFM_Processor_setCarrierRatio(synthFM_Processor__ctx_type_2 &_ctx, fix16_t ratio, uint8_t force){
   if(synthFM_Util_change(_ctx._inst333b,ratio) || force){
      synthFM_Voice_synthSetCarrierRatio(_ctx.voice,ratio);
   }
};

typedef synthFM_Processor__ctx_type_2 synthFM_Processor_setModulatorLevel_type;

static_inline void synthFM_Processor_setModulatorLevel_init(synthFM_Processor__ctx_type_2 &_output_){
   synthFM_Processor__ctx_type_2_init(_output_);
   return ;
}

static_inline void synthFM_Processor_setModulatorLevel(synthFM_Processor__ctx_type_2 &_ctx, fix16_t level, uint8_t force){
   if(synthFM_Util_change(_ctx._inst363b,level) || force){
      synthFM_Voice_synthSetModulatorLevel(_ctx.voice,level);
   }
};

typedef synthFM_Processor__ctx_type_2 synthFM_Processor_setModulatorMode_type;

static_inline void synthFM_Processor_setModulatorMode_init(synthFM_Processor__ctx_type_2 &_output_){
   synthFM_Processor__ctx_type_2_init(_output_);
   return ;
}

static_inline void synthFM_Processor_setModulatorMode(synthFM_Processor__ctx_type_2 &_ctx, fix16_t mode, uint8_t force){
   if(synthFM_Util_change(_ctx._inst393b,mode) || force){
      if(mode > 0x0 /* 0.000000 */){
         synthFM_Voice_synthSetModulatorTargetLevel(_ctx.voice,false);
      }
      else
      {
         synthFM_Voice_synthSetModulatorTargetLevel(_ctx.voice,true);
      }
   }
};

typedef synthFM_Processor__ctx_type_2 synthFM_Processor_setModulatorPhaseShift_type;

static_inline void synthFM_Processor_setModulatorPhaseShift_init(synthFM_Processor__ctx_type_2 &_output_){
   synthFM_Processor__ctx_type_2_init(_output_);
   return ;
}

static_inline void synthFM_Processor_setModulatorPhaseShift(synthFM_Processor__ctx_type_2 &_ctx, fix16_t ratio, uint8_t force){
   if(synthFM_Util_change(_ctx._inst443b,ratio) || force){
      synthFM_Voice_synthSetModulatorPhaseShift(_ctx.voice,ratio);
   }
};

typedef synthFM_Processor__ctx_type_2 synthFM_Processor_setModulatorFeedback_type;

static_inline void synthFM_Processor_setModulatorFeedback_init(synthFM_Processor__ctx_type_2 &_output_){
   synthFM_Processor__ctx_type_2_init(_output_);
   return ;
}

static_inline void synthFM_Processor_setModulatorFeedback(synthFM_Processor__ctx_type_2 &_ctx, fix16_t ratio, uint8_t force){
   if(synthFM_Util_change(_ctx._inst473b,ratio) || force){
      synthFM_Voice_synthSetModulatorFeedback(_ctx.voice,ratio);
   }
};

typedef synthFM_Processor__ctx_type_2 synthFM_Processor_setModulatorADSR_type;

static_inline void synthFM_Processor_setModulatorADSR_init(synthFM_Processor__ctx_type_2 &_output_){
   synthFM_Processor__ctx_type_2_init(_output_);
   return ;
}

static_inline void synthFM_Processor_setModulatorADSR(synthFM_Processor__ctx_type_2 &_ctx, fix16_t a, fix16_t d, fix16_t s, fix16_t r, uint8_t force){
   if(synthFM_Processor_change4(_ctx._inst5036,a,d,s,r) || force){
      synthFM_Voice_synthSetModulatorADSR(_ctx.voice,a,d,s,r);
   }
};

typedef synthFM_Processor__ctx_type_2 synthFM_Processor_setCarrierADSR_type;

static_inline void synthFM_Processor_setCarrierADSR_init(synthFM_Processor__ctx_type_2 &_output_){
   synthFM_Processor__ctx_type_2_init(_output_);
   return ;
}

static_inline void synthFM_Processor_setCarrierADSR(synthFM_Processor__ctx_type_2 &_ctx, fix16_t a, fix16_t d, fix16_t s, fix16_t r, uint8_t force){
   if(synthFM_Processor_change4(_ctx._inst5336,a,d,s,r) || force){
      synthFM_Voice_synthSetCarrierADSR(_ctx.voice,a,d,s,r);
   }
};

typedef synthFM_Processor__ctx_type_2 synthFM_Processor_default_type;

static_inline void synthFM_Processor_default_init(synthFM_Processor__ctx_type_2 &_output_){
   synthFM_Processor__ctx_type_2_init(_output_);
   return ;
}

static_inline void synthFM_Processor_default(synthFM_Processor__ctx_type_2 &_ctx){
   synthFM_Voice_default(_ctx.voice);
   synthFM_Processor_setSamplerate(_ctx,0x2c1999 /* 44.100000 */);
   synthFM_Voice_setReuse(_ctx.voice,true);
}



#endif // ENGINE_SYNTHFM_H
