
/* Code automatically generated by Vult https://github.com/modlfo/vult */
#ifndef ENGINE_SYNTHSAMPLERCLARINETS_H
#define ENGINE_SYNTHSAMPLERCLARINETS_H
#include <stdint.h>
#include <math.h>
#include "vultin.h"
#include "engine_synthSamplerClarinets.tables.h"

static_inline fix16_t synthSamplerClarinets_Util_noteToFrequency(int note){
   return fix_mul(0x217 /* 0.008176 */,fix_exp(fix_mul(0xec9 /* 0.057762 */,int_to_fix(note))));
};

typedef struct synthSamplerClarinets_Util__ctx_type_1 {
   uint8_t pre;
} synthSamplerClarinets_Util__ctx_type_1;

typedef synthSamplerClarinets_Util__ctx_type_1 synthSamplerClarinets_Util_edge_type;

static_inline void synthSamplerClarinets_Util__ctx_type_1_init(synthSamplerClarinets_Util__ctx_type_1 &_output_){
   synthSamplerClarinets_Util__ctx_type_1 _ctx;
   _ctx.pre = false;
   _output_ = _ctx;
   return ;
}

static_inline void synthSamplerClarinets_Util_edge_init(synthSamplerClarinets_Util__ctx_type_1 &_output_){
   synthSamplerClarinets_Util__ctx_type_1_init(_output_);
   return ;
}

static_inline uint8_t synthSamplerClarinets_Util_edge(synthSamplerClarinets_Util__ctx_type_1 &_ctx, uint8_t x){
   uint8_t ret;
   ret = (x && bool_not(_ctx.pre));
   _ctx.pre = x;
   return ret;
}

static_inline fix16_t synthSamplerClarinets_Util_cubic_clipper(fix16_t x){
   if(x <= -0xaaaa /* -0.666667 */){
      return -0xaaaa /* -0.666667 */;
   }
   else
   {
      if(x >= 0xaaaa /* 0.666667 */){
         return 0xaaaa /* 0.666667 */;
      }
      else
      {
         return (x + fix_mul(fix_mul(fix_mul(-0x5555 /* -0.333333 */,x),x),x));
      }
   }
};

typedef struct synthSamplerClarinets_Util__ctx_type_3 {
   fix16_t pre_x;
} synthSamplerClarinets_Util__ctx_type_3;

typedef synthSamplerClarinets_Util__ctx_type_3 synthSamplerClarinets_Util_change_type;

static_inline void synthSamplerClarinets_Util__ctx_type_3_init(synthSamplerClarinets_Util__ctx_type_3 &_output_){
   synthSamplerClarinets_Util__ctx_type_3 _ctx;
   _ctx.pre_x = 0x0 /* 0.000000 */;
   _output_ = _ctx;
   return ;
}

static_inline void synthSamplerClarinets_Util_change_init(synthSamplerClarinets_Util__ctx_type_3 &_output_){
   synthSamplerClarinets_Util__ctx_type_3_init(_output_);
   return ;
}

static_inline uint8_t synthSamplerClarinets_Util_change(synthSamplerClarinets_Util__ctx_type_3 &_ctx, fix16_t x){
   uint8_t v;
   v = (_ctx.pre_x != x);
   _ctx.pre_x = x;
   return v;
}

typedef struct synthSamplerClarinets_Util__ctx_type_4 {
   fix16_t x;
} synthSamplerClarinets_Util__ctx_type_4;

typedef synthSamplerClarinets_Util__ctx_type_4 synthSamplerClarinets_Util_smooth_type;

static_inline void synthSamplerClarinets_Util__ctx_type_4_init(synthSamplerClarinets_Util__ctx_type_4 &_output_){
   synthSamplerClarinets_Util__ctx_type_4 _ctx;
   _ctx.x = 0x0 /* 0.000000 */;
   _output_ = _ctx;
   return ;
}

static_inline void synthSamplerClarinets_Util_smooth_init(synthSamplerClarinets_Util__ctx_type_4 &_output_){
   synthSamplerClarinets_Util__ctx_type_4_init(_output_);
   return ;
}

static_inline fix16_t synthSamplerClarinets_Util_smooth(synthSamplerClarinets_Util__ctx_type_4 &_ctx, fix16_t input, fix16_t coeff){
   _ctx.x = (_ctx.x + fix_mul(coeff,(input + (- _ctx.x))));
   return _ctx.x;
}

static_inline fix16_t synthSamplerClarinets_Util_velocityToLevel(int velocity){
   velocity = int_clip(velocity,0,127);
   return fix_mul(0x204 /* 0.007874 */,int_to_fix(velocity));
}

static_inline int synthSamplerClarinets_SampleWrapper_sample_samples(){
   return 34725;
};

static_inline fix16_t synthSamplerClarinets_SampleWrapper_sample(int channel, int index){
   if(channel == 0){
      return fix_wrap_array(synthSamplerClarinets_SampleWrapper_sample_chan_0)[(index % 34725)];
   }
   return 0x0 /* 0.000000 */;
}

static_inline fix16_t synthSamplerClarinets_SampleWrapper_getSample(int index){
   return synthSamplerClarinets_SampleWrapper_sample(0,index);
};

static_inline int synthSamplerClarinets_SampleWrapper_getSampleSize(){
   return synthSamplerClarinets_SampleWrapper_sample_samples();
};

static_inline fix16_t synthSamplerClarinets_SampleWrapper_getSampleFs(){
   return 0x1e0000 /* 30.000000 */;
};

static_inline int synthSamplerClarinets_SampleWrapper_getSampleNote(){
   return 60;
};

static_inline uint8_t synthSamplerClarinets_SampleWrapper_isSampleLoop(){
   return false;
};

static_inline int synthSamplerClarinets_SampleWrapper_getSampleLoopStart(){
   return (-1);
};

static_inline int synthSamplerClarinets_SampleWrapper_getSampleLoopEnd(){
   return (-1);
};

typedef struct synthSamplerClarinets_Notes__ctx_type_0 {
   uint8_t poly;
   int notes[128];
   int nb_notes;
   int last_notes[128];
} synthSamplerClarinets_Notes__ctx_type_0;

typedef synthSamplerClarinets_Notes__ctx_type_0 synthSamplerClarinets_Notes_setPoly_type;

void synthSamplerClarinets_Notes__ctx_type_0_init(synthSamplerClarinets_Notes__ctx_type_0 &_output_);

static_inline void synthSamplerClarinets_Notes_setPoly_init(synthSamplerClarinets_Notes__ctx_type_0 &_output_){
   synthSamplerClarinets_Notes__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Notes_setPoly(synthSamplerClarinets_Notes__ctx_type_0 &_ctx, uint8_t flag){
   _ctx.poly = flag;
};

typedef synthSamplerClarinets_Notes__ctx_type_0 synthSamplerClarinets_Notes_default_type;

static_inline void synthSamplerClarinets_Notes_default_init(synthSamplerClarinets_Notes__ctx_type_0 &_output_){
   synthSamplerClarinets_Notes__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Notes_default(synthSamplerClarinets_Notes__ctx_type_0 &_ctx){
   synthSamplerClarinets_Notes_setPoly(_ctx,false);
};

typedef synthSamplerClarinets_Notes__ctx_type_0 synthSamplerClarinets_Notes_nbNotes_type;

static_inline void synthSamplerClarinets_Notes_nbNotes_init(synthSamplerClarinets_Notes__ctx_type_0 &_output_){
   synthSamplerClarinets_Notes__ctx_type_0_init(_output_);
   return ;
}

static_inline int synthSamplerClarinets_Notes_nbNotes(synthSamplerClarinets_Notes__ctx_type_0 &_ctx){
   return _ctx.nb_notes;
};

typedef synthSamplerClarinets_Notes__ctx_type_0 synthSamplerClarinets_Notes_firstNote_type;

static_inline void synthSamplerClarinets_Notes_firstNote_init(synthSamplerClarinets_Notes__ctx_type_0 &_output_){
   synthSamplerClarinets_Notes__ctx_type_0_init(_output_);
   return ;
}

int synthSamplerClarinets_Notes_firstNote(synthSamplerClarinets_Notes__ctx_type_0 &_ctx);

typedef synthSamplerClarinets_Notes__ctx_type_0 synthSamplerClarinets_Notes_lastNote_type;

static_inline void synthSamplerClarinets_Notes_lastNote_init(synthSamplerClarinets_Notes__ctx_type_0 &_output_){
   synthSamplerClarinets_Notes__ctx_type_0_init(_output_);
   return ;
}

int synthSamplerClarinets_Notes_lastNote(synthSamplerClarinets_Notes__ctx_type_0 &_ctx);

typedef synthSamplerClarinets_Notes__ctx_type_0 synthSamplerClarinets_Notes_noteOn_type;

static_inline void synthSamplerClarinets_Notes_noteOn_init(synthSamplerClarinets_Notes__ctx_type_0 &_output_){
   synthSamplerClarinets_Notes__ctx_type_0_init(_output_);
   return ;
}

uint8_t synthSamplerClarinets_Notes_noteOn(synthSamplerClarinets_Notes__ctx_type_0 &_ctx, int note, int velocity, int channel);

typedef synthSamplerClarinets_Notes__ctx_type_0 synthSamplerClarinets_Notes_noteOff_type;

static_inline void synthSamplerClarinets_Notes_noteOff_init(synthSamplerClarinets_Notes__ctx_type_0 &_output_){
   synthSamplerClarinets_Notes__ctx_type_0_init(_output_);
   return ;
}

uint8_t synthSamplerClarinets_Notes_noteOff(synthSamplerClarinets_Notes__ctx_type_0 &_ctx, int note, int channel);

static_inline void synthSamplerClarinets_Buffer_buffer(fix16_t (&oBuff)[256]){
}

void synthSamplerClarinets_Buffer_buffer_large(fix16_t (&oBuff)[2048]);

typedef struct synthSamplerClarinets_Sampler__ctx_type_0 {
   fix16_t step;
   int state;
   int size;
   int sampleNote;
   fix16_t sampleFs;
   int posBase;
   fix16_t pos;
   synthSamplerClarinets_Notes__ctx_type_0 playingnotes;
   fix16_t noteRatio;
   uint8_t loopy;
   int loopS;
   int loopE;
   fix16_t level;
   uint8_t gate;
   fix16_t fsRatio;
   fix16_t fs;
   uint8_t crossfade;
   fix16_t buffer_o[256];
   fix16_t buffer_cross[256];
} synthSamplerClarinets_Sampler__ctx_type_0;

typedef synthSamplerClarinets_Sampler__ctx_type_0 synthSamplerClarinets_Sampler_process_type;

void synthSamplerClarinets_Sampler__ctx_type_0_init(synthSamplerClarinets_Sampler__ctx_type_0 &_output_);

static_inline void synthSamplerClarinets_Sampler_process_init(synthSamplerClarinets_Sampler__ctx_type_0 &_output_){
   synthSamplerClarinets_Sampler__ctx_type_0_init(_output_);
   return ;
}

fix16_t synthSamplerClarinets_Sampler_process(synthSamplerClarinets_Sampler__ctx_type_0 &_ctx);

typedef synthSamplerClarinets_Sampler__ctx_type_0 synthSamplerClarinets_Sampler_process_bufferTo_type;

static_inline void synthSamplerClarinets_Sampler_process_bufferTo_init(synthSamplerClarinets_Sampler__ctx_type_0 &_output_){
   synthSamplerClarinets_Sampler__ctx_type_0_init(_output_);
   return ;
}

void synthSamplerClarinets_Sampler_process_bufferTo(synthSamplerClarinets_Sampler__ctx_type_0 &_ctx, int nb, fix16_t (&oBuffer)[256]);

typedef synthSamplerClarinets_Sampler__ctx_type_0 synthSamplerClarinets_Sampler_process_buffer_type;

static_inline void synthSamplerClarinets_Sampler_process_buffer_init(synthSamplerClarinets_Sampler__ctx_type_0 &_output_){
   synthSamplerClarinets_Sampler__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Sampler_process_buffer(synthSamplerClarinets_Sampler__ctx_type_0 &_ctx, int nb){
   synthSamplerClarinets_Sampler_process_bufferTo(_ctx,nb,_ctx.buffer_o);
};

typedef synthSamplerClarinets_Sampler__ctx_type_0 synthSamplerClarinets_Sampler_updateStep_type;

static_inline void synthSamplerClarinets_Sampler_updateStep_init(synthSamplerClarinets_Sampler__ctx_type_0 &_output_){
   synthSamplerClarinets_Sampler__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Sampler_updateStep(synthSamplerClarinets_Sampler__ctx_type_0 &_ctx){
   _ctx.step = fix_mul(_ctx.fsRatio,_ctx.noteRatio);
};

typedef synthSamplerClarinets_Sampler__ctx_type_0 synthSamplerClarinets_Sampler_setSamplerate_type;

static_inline void synthSamplerClarinets_Sampler_setSamplerate_init(synthSamplerClarinets_Sampler__ctx_type_0 &_output_){
   synthSamplerClarinets_Sampler__ctx_type_0_init(_output_);
   return ;
}

void synthSamplerClarinets_Sampler_setSamplerate(synthSamplerClarinets_Sampler__ctx_type_0 &_ctx, fix16_t newFs);

typedef synthSamplerClarinets_Sampler__ctx_type_0 synthSamplerClarinets_Sampler_updateCrossFade_type;

static_inline void synthSamplerClarinets_Sampler_updateCrossFade_init(synthSamplerClarinets_Sampler__ctx_type_0 &_output_){
   synthSamplerClarinets_Sampler__ctx_type_0_init(_output_);
   return ;
}

void synthSamplerClarinets_Sampler_updateCrossFade(synthSamplerClarinets_Sampler__ctx_type_0 &_ctx);

typedef synthSamplerClarinets_Sampler__ctx_type_0 synthSamplerClarinets_Sampler_setLoop_type;

static_inline void synthSamplerClarinets_Sampler_setLoop_init(synthSamplerClarinets_Sampler__ctx_type_0 &_output_){
   synthSamplerClarinets_Sampler__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Sampler_setLoop(synthSamplerClarinets_Sampler__ctx_type_0 &_ctx, uint8_t loop){
   _ctx.loopy = loop;
};

typedef synthSamplerClarinets_Sampler__ctx_type_0 synthSamplerClarinets_Sampler_setLoopStart_type;

static_inline void synthSamplerClarinets_Sampler_setLoopStart_init(synthSamplerClarinets_Sampler__ctx_type_0 &_output_){
   synthSamplerClarinets_Sampler__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Sampler_setLoopStart(synthSamplerClarinets_Sampler__ctx_type_0 &_ctx, int newLoopS){
   _ctx.loopS = int_clip(newLoopS,0,_ctx.size);
   synthSamplerClarinets_Sampler_updateCrossFade(_ctx);
}

typedef synthSamplerClarinets_Sampler__ctx_type_0 synthSamplerClarinets_Sampler_setLoopEnd_type;

static_inline void synthSamplerClarinets_Sampler_setLoopEnd_init(synthSamplerClarinets_Sampler__ctx_type_0 &_output_){
   synthSamplerClarinets_Sampler__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Sampler_setLoopEnd(synthSamplerClarinets_Sampler__ctx_type_0 &_ctx, int newLoopE){
   _ctx.loopE = int_clip(newLoopE,0,_ctx.size);
   synthSamplerClarinets_Sampler_updateCrossFade(_ctx);
}

typedef synthSamplerClarinets_Sampler__ctx_type_0 synthSamplerClarinets_Sampler_getLoop_type;

static_inline void synthSamplerClarinets_Sampler_getLoop_init(synthSamplerClarinets_Sampler__ctx_type_0 &_output_){
   synthSamplerClarinets_Sampler__ctx_type_0_init(_output_);
   return ;
}

static_inline uint8_t synthSamplerClarinets_Sampler_getLoop(synthSamplerClarinets_Sampler__ctx_type_0 &_ctx){
   return _ctx.loopy;
};

typedef synthSamplerClarinets_Sampler__ctx_type_0 synthSamplerClarinets_Sampler_getLoopStart_type;

static_inline void synthSamplerClarinets_Sampler_getLoopStart_init(synthSamplerClarinets_Sampler__ctx_type_0 &_output_){
   synthSamplerClarinets_Sampler__ctx_type_0_init(_output_);
   return ;
}

static_inline int synthSamplerClarinets_Sampler_getLoopStart(synthSamplerClarinets_Sampler__ctx_type_0 &_ctx){
   return _ctx.loopS;
};

typedef synthSamplerClarinets_Sampler__ctx_type_0 synthSamplerClarinets_Sampler_getLoopEnd_type;

static_inline void synthSamplerClarinets_Sampler_getLoopEnd_init(synthSamplerClarinets_Sampler__ctx_type_0 &_output_){
   synthSamplerClarinets_Sampler__ctx_type_0_init(_output_);
   return ;
}

static_inline int synthSamplerClarinets_Sampler_getLoopEnd(synthSamplerClarinets_Sampler__ctx_type_0 &_ctx){
   return _ctx.loopE;
};

typedef synthSamplerClarinets_Sampler__ctx_type_0 synthSamplerClarinets_Sampler_getSampleSize_type;

static_inline void synthSamplerClarinets_Sampler_getSampleSize_init(synthSamplerClarinets_Sampler__ctx_type_0 &_output_){
   synthSamplerClarinets_Sampler__ctx_type_0_init(_output_);
   return ;
}

static_inline int synthSamplerClarinets_Sampler_getSampleSize(synthSamplerClarinets_Sampler__ctx_type_0 &_ctx){
   return _ctx.size;
};

typedef synthSamplerClarinets_Sampler__ctx_type_0 synthSamplerClarinets_Sampler_setNote_type;

static_inline void synthSamplerClarinets_Sampler_setNote_init(synthSamplerClarinets_Sampler__ctx_type_0 &_output_){
   synthSamplerClarinets_Sampler__ctx_type_0_init(_output_);
   return ;
}

void synthSamplerClarinets_Sampler_setNote(synthSamplerClarinets_Sampler__ctx_type_0 &_ctx, int note);

typedef synthSamplerClarinets_Sampler__ctx_type_0 synthSamplerClarinets_Sampler_setLevel_type;

static_inline void synthSamplerClarinets_Sampler_setLevel_init(synthSamplerClarinets_Sampler__ctx_type_0 &_output_){
   synthSamplerClarinets_Sampler__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Sampler_setLevel(synthSamplerClarinets_Sampler__ctx_type_0 &_ctx, fix16_t newLevel){
   _ctx.level = newLevel;
};

typedef synthSamplerClarinets_Sampler__ctx_type_0 synthSamplerClarinets_Sampler_noteOn_type;

static_inline void synthSamplerClarinets_Sampler_noteOn_init(synthSamplerClarinets_Sampler__ctx_type_0 &_output_){
   synthSamplerClarinets_Sampler__ctx_type_0_init(_output_);
   return ;
}

void synthSamplerClarinets_Sampler_noteOn(synthSamplerClarinets_Sampler__ctx_type_0 &_ctx, int note, int velocity, int channel);

typedef synthSamplerClarinets_Sampler__ctx_type_0 synthSamplerClarinets_Sampler_setPoly_type;

static_inline void synthSamplerClarinets_Sampler_setPoly_init(synthSamplerClarinets_Sampler__ctx_type_0 &_output_){
   synthSamplerClarinets_Sampler__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Sampler_setPoly(synthSamplerClarinets_Sampler__ctx_type_0 &_ctx, uint8_t flag){
   synthSamplerClarinets_Notes_setPoly(_ctx.playingnotes,flag);
};

typedef synthSamplerClarinets_Sampler__ctx_type_0 synthSamplerClarinets_Sampler_noteOff_type;

static_inline void synthSamplerClarinets_Sampler_noteOff_init(synthSamplerClarinets_Sampler__ctx_type_0 &_output_){
   synthSamplerClarinets_Sampler__ctx_type_0_init(_output_);
   return ;
}

void synthSamplerClarinets_Sampler_noteOff(synthSamplerClarinets_Sampler__ctx_type_0 &_ctx, int note, int channel);

typedef synthSamplerClarinets_Sampler__ctx_type_0 synthSamplerClarinets_Sampler_default_type;

static_inline void synthSamplerClarinets_Sampler_default_init(synthSamplerClarinets_Sampler__ctx_type_0 &_output_){
   synthSamplerClarinets_Sampler__ctx_type_0_init(_output_);
   return ;
}

void synthSamplerClarinets_Sampler_default(synthSamplerClarinets_Sampler__ctx_type_0 &_ctx);

typedef struct synthSamplerClarinets_Sampler__ctx_type_1 {
   synthSamplerClarinets_Sampler__ctx_type_0 _inst1fd;
} synthSamplerClarinets_Sampler__ctx_type_1;

typedef synthSamplerClarinets_Sampler__ctx_type_1 synthSamplerClarinets_Sampler_dummy_type;

static_inline void synthSamplerClarinets_Sampler__ctx_type_1_init(synthSamplerClarinets_Sampler__ctx_type_1 &_output_){
   synthSamplerClarinets_Sampler__ctx_type_1 _ctx;
   synthSamplerClarinets_Sampler__ctx_type_0_init(_ctx._inst1fd);
   _output_ = _ctx;
   return ;
}

static_inline void synthSamplerClarinets_Sampler_dummy_init(synthSamplerClarinets_Sampler__ctx_type_1 &_output_){
   synthSamplerClarinets_Sampler__ctx_type_1_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Sampler_dummy(synthSamplerClarinets_Sampler__ctx_type_1 &_ctx){
   fix16_t buff[256];
   synthSamplerClarinets_Buffer_buffer(buff);
   synthSamplerClarinets_Sampler_process_bufferTo(_ctx._inst1fd,0,buff);
}

typedef struct synthSamplerClarinets_Poly__ctx_type_0 {
   synthSamplerClarinets_Sampler__ctx_type_0 voice3;
   synthSamplerClarinets_Sampler__ctx_type_0 voice2;
   synthSamplerClarinets_Sampler__ctx_type_0 voice1;
   synthSamplerClarinets_Sampler__ctx_type_0 voice0;
   uint8_t should_leftovers;
} synthSamplerClarinets_Poly__ctx_type_0;

typedef synthSamplerClarinets_Poly__ctx_type_0 synthSamplerClarinets_Poly_getSample_type;

void synthSamplerClarinets_Poly__ctx_type_0_init(synthSamplerClarinets_Poly__ctx_type_0 &_output_);

static_inline void synthSamplerClarinets_Poly_getSample_init(synthSamplerClarinets_Poly__ctx_type_0 &_output_){
   synthSamplerClarinets_Poly__ctx_type_0_init(_output_);
   return ;
}

fix16_t synthSamplerClarinets_Poly_getSample(synthSamplerClarinets_Poly__ctx_type_0 &_ctx, int voice);

typedef synthSamplerClarinets_Poly__ctx_type_0 synthSamplerClarinets_Poly_runVoice_type;

static_inline void synthSamplerClarinets_Poly_runVoice_init(synthSamplerClarinets_Poly__ctx_type_0 &_output_){
   synthSamplerClarinets_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Poly_runVoice(synthSamplerClarinets_Poly__ctx_type_0 &_ctx, int voice, int nb, fix16_t (&buff)[256]){
   switch(voice) {
      case 0:
         synthSamplerClarinets_Sampler_process_bufferTo(_ctx.voice0,nb,buff);
      break;
      case 1:
         synthSamplerClarinets_Sampler_process_bufferTo(_ctx.voice1,nb,buff);
      break;
      case 2:
         synthSamplerClarinets_Sampler_process_bufferTo(_ctx.voice2,nb,buff);
      break;
      case 3:
         synthSamplerClarinets_Sampler_process_bufferTo(_ctx.voice3,nb,buff);
      break;
    
   }
};

typedef synthSamplerClarinets_Poly__ctx_type_0 synthSamplerClarinets_Poly_sendNoteOn_type;

static_inline void synthSamplerClarinets_Poly_sendNoteOn_init(synthSamplerClarinets_Poly__ctx_type_0 &_output_){
   synthSamplerClarinets_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Poly_sendNoteOn(synthSamplerClarinets_Poly__ctx_type_0 &_ctx, int voice, int note, int velocity, int channel){
   switch(voice) {
      case 0:
         synthSamplerClarinets_Sampler_noteOn(_ctx.voice0,note,velocity,channel);
      break;
      case 1:
         synthSamplerClarinets_Sampler_noteOn(_ctx.voice1,note,velocity,channel);
      break;
      case 2:
         synthSamplerClarinets_Sampler_noteOn(_ctx.voice2,note,velocity,channel);
      break;
      case 3:
         synthSamplerClarinets_Sampler_noteOn(_ctx.voice3,note,velocity,channel);
      break;
    
   }
};

typedef synthSamplerClarinets_Poly__ctx_type_0 synthSamplerClarinets_Poly_sendNoteOff_type;

static_inline void synthSamplerClarinets_Poly_sendNoteOff_init(synthSamplerClarinets_Poly__ctx_type_0 &_output_){
   synthSamplerClarinets_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Poly_sendNoteOff(synthSamplerClarinets_Poly__ctx_type_0 &_ctx, int voice, int note, int channel){
   switch(voice) {
      case 0:
         synthSamplerClarinets_Sampler_noteOff(_ctx.voice0,note,channel);
      break;
      case 1:
         synthSamplerClarinets_Sampler_noteOff(_ctx.voice1,note,channel);
      break;
      case 2:
         synthSamplerClarinets_Sampler_noteOff(_ctx.voice2,note,channel);
      break;
      case 3:
         synthSamplerClarinets_Sampler_noteOff(_ctx.voice3,note,channel);
      break;
    
   }
};

typedef synthSamplerClarinets_Poly__ctx_type_0 synthSamplerClarinets_Poly_setSamplerate_type;

static_inline void synthSamplerClarinets_Poly_setSamplerate_init(synthSamplerClarinets_Poly__ctx_type_0 &_output_){
   synthSamplerClarinets_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Poly_setSamplerate(synthSamplerClarinets_Poly__ctx_type_0 &_ctx, fix16_t fs){
   synthSamplerClarinets_Sampler_setSamplerate(_ctx.voice0,fs);
   synthSamplerClarinets_Sampler_setSamplerate(_ctx.voice1,fs);
   synthSamplerClarinets_Sampler_setSamplerate(_ctx.voice2,fs);
   synthSamplerClarinets_Sampler_setSamplerate(_ctx.voice3,fs);
}

typedef synthSamplerClarinets_Poly__ctx_type_0 synthSamplerClarinets_Poly_synthSetLoop_type;

static_inline void synthSamplerClarinets_Poly_synthSetLoop_init(synthSamplerClarinets_Poly__ctx_type_0 &_output_){
   synthSamplerClarinets_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Poly_synthSetLoop(synthSamplerClarinets_Poly__ctx_type_0 &_ctx, uint8_t flag){
   synthSamplerClarinets_Sampler_setLoop(_ctx.voice0,flag);
   synthSamplerClarinets_Sampler_setLoop(_ctx.voice1,flag);
   synthSamplerClarinets_Sampler_setLoop(_ctx.voice2,flag);
   synthSamplerClarinets_Sampler_setLoop(_ctx.voice3,flag);
}

typedef synthSamplerClarinets_Poly__ctx_type_0 synthSamplerClarinets_Poly_synthSetLoopStart_type;

static_inline void synthSamplerClarinets_Poly_synthSetLoopStart_init(synthSamplerClarinets_Poly__ctx_type_0 &_output_){
   synthSamplerClarinets_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Poly_synthSetLoopStart(synthSamplerClarinets_Poly__ctx_type_0 &_ctx, int value){
   synthSamplerClarinets_Sampler_setLoopStart(_ctx.voice0,value);
   synthSamplerClarinets_Sampler_setLoopStart(_ctx.voice1,value);
   synthSamplerClarinets_Sampler_setLoopStart(_ctx.voice2,value);
   synthSamplerClarinets_Sampler_setLoopStart(_ctx.voice3,value);
}

typedef synthSamplerClarinets_Poly__ctx_type_0 synthSamplerClarinets_Poly_synthSetLoopEnd_type;

static_inline void synthSamplerClarinets_Poly_synthSetLoopEnd_init(synthSamplerClarinets_Poly__ctx_type_0 &_output_){
   synthSamplerClarinets_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Poly_synthSetLoopEnd(synthSamplerClarinets_Poly__ctx_type_0 &_ctx, int value){
   synthSamplerClarinets_Sampler_setLoopEnd(_ctx.voice0,value);
   synthSamplerClarinets_Sampler_setLoopEnd(_ctx.voice1,value);
   synthSamplerClarinets_Sampler_setLoopEnd(_ctx.voice2,value);
   synthSamplerClarinets_Sampler_setLoopEnd(_ctx.voice3,value);
}

typedef synthSamplerClarinets_Poly__ctx_type_0 synthSamplerClarinets_Poly_synthGetLoop_type;

static_inline void synthSamplerClarinets_Poly_synthGetLoop_init(synthSamplerClarinets_Poly__ctx_type_0 &_output_){
   synthSamplerClarinets_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline uint8_t synthSamplerClarinets_Poly_synthGetLoop(synthSamplerClarinets_Poly__ctx_type_0 &_ctx){
   return synthSamplerClarinets_Sampler_getLoop(_ctx.voice0);
};

typedef synthSamplerClarinets_Poly__ctx_type_0 synthSamplerClarinets_Poly_synthGetLoopStart_type;

static_inline void synthSamplerClarinets_Poly_synthGetLoopStart_init(synthSamplerClarinets_Poly__ctx_type_0 &_output_){
   synthSamplerClarinets_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline int synthSamplerClarinets_Poly_synthGetLoopStart(synthSamplerClarinets_Poly__ctx_type_0 &_ctx){
   return synthSamplerClarinets_Sampler_getLoopStart(_ctx.voice0);
};

typedef synthSamplerClarinets_Poly__ctx_type_0 synthSamplerClarinets_Poly_synthGetLoopEnd_type;

static_inline void synthSamplerClarinets_Poly_synthGetLoopEnd_init(synthSamplerClarinets_Poly__ctx_type_0 &_output_){
   synthSamplerClarinets_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline int synthSamplerClarinets_Poly_synthGetLoopEnd(synthSamplerClarinets_Poly__ctx_type_0 &_ctx){
   return synthSamplerClarinets_Sampler_getLoopEnd(_ctx.voice0);
};

typedef synthSamplerClarinets_Poly__ctx_type_0 synthSamplerClarinets_Poly_synthGetSize_type;

static_inline void synthSamplerClarinets_Poly_synthGetSize_init(synthSamplerClarinets_Poly__ctx_type_0 &_output_){
   synthSamplerClarinets_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline int synthSamplerClarinets_Poly_synthGetSize(synthSamplerClarinets_Poly__ctx_type_0 &_ctx){
   return synthSamplerClarinets_Sampler_getSampleSize(_ctx.voice0);
};

typedef synthSamplerClarinets_Poly__ctx_type_0 synthSamplerClarinets_Poly_synthGetNbWavetables_type;

static_inline void synthSamplerClarinets_Poly_synthGetNbWavetables_init(synthSamplerClarinets_Poly__ctx_type_0 &_output_){
   synthSamplerClarinets_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline int synthSamplerClarinets_Poly_synthGetNbWavetables(synthSamplerClarinets_Poly__ctx_type_0 &_ctx){
   return 0;
};

typedef synthSamplerClarinets_Poly__ctx_type_0 synthSamplerClarinets_Poly_synthSetModulatorWavetable_type;

static_inline void synthSamplerClarinets_Poly_synthSetModulatorWavetable_init(synthSamplerClarinets_Poly__ctx_type_0 &_output_){
   synthSamplerClarinets_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Poly_synthSetModulatorWavetable(synthSamplerClarinets_Poly__ctx_type_0 &_ctx, fix16_t wavetableIdx){
}

typedef synthSamplerClarinets_Poly__ctx_type_0 synthSamplerClarinets_Poly_synthSetModulatorWavetablePhase_type;

static_inline void synthSamplerClarinets_Poly_synthSetModulatorWavetablePhase_init(synthSamplerClarinets_Poly__ctx_type_0 &_output_){
   synthSamplerClarinets_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Poly_synthSetModulatorWavetablePhase(synthSamplerClarinets_Poly__ctx_type_0 &_ctx, fix16_t phaseIdx){
}

typedef synthSamplerClarinets_Poly__ctx_type_0 synthSamplerClarinets_Poly_synthSetCarrierWavetable_type;

static_inline void synthSamplerClarinets_Poly_synthSetCarrierWavetable_init(synthSamplerClarinets_Poly__ctx_type_0 &_output_){
   synthSamplerClarinets_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Poly_synthSetCarrierWavetable(synthSamplerClarinets_Poly__ctx_type_0 &_ctx, fix16_t wavetableIdx){
}

typedef synthSamplerClarinets_Poly__ctx_type_0 synthSamplerClarinets_Poly_synthSetCarrierWavetablePhase_type;

static_inline void synthSamplerClarinets_Poly_synthSetCarrierWavetablePhase_init(synthSamplerClarinets_Poly__ctx_type_0 &_output_){
   synthSamplerClarinets_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Poly_synthSetCarrierWavetablePhase(synthSamplerClarinets_Poly__ctx_type_0 &_ctx, fix16_t phaseIdx){
}

typedef synthSamplerClarinets_Poly__ctx_type_0 synthSamplerClarinets_Poly_synthSetModulatorRatio_type;

static_inline void synthSamplerClarinets_Poly_synthSetModulatorRatio_init(synthSamplerClarinets_Poly__ctx_type_0 &_output_){
   synthSamplerClarinets_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Poly_synthSetModulatorRatio(synthSamplerClarinets_Poly__ctx_type_0 &_ctx, fix16_t ratio){
}

typedef synthSamplerClarinets_Poly__ctx_type_0 synthSamplerClarinets_Poly_synthSetCarrierRatio_type;

static_inline void synthSamplerClarinets_Poly_synthSetCarrierRatio_init(synthSamplerClarinets_Poly__ctx_type_0 &_output_){
   synthSamplerClarinets_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Poly_synthSetCarrierRatio(synthSamplerClarinets_Poly__ctx_type_0 &_ctx, fix16_t ratio){
}

typedef synthSamplerClarinets_Poly__ctx_type_0 synthSamplerClarinets_Poly_synthSetModulatorLevel_type;

static_inline void synthSamplerClarinets_Poly_synthSetModulatorLevel_init(synthSamplerClarinets_Poly__ctx_type_0 &_output_){
   synthSamplerClarinets_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Poly_synthSetModulatorLevel(synthSamplerClarinets_Poly__ctx_type_0 &_ctx, fix16_t level){
}

typedef synthSamplerClarinets_Poly__ctx_type_0 synthSamplerClarinets_Poly_synthSetModulatorTargetLevel_type;

static_inline void synthSamplerClarinets_Poly_synthSetModulatorTargetLevel_init(synthSamplerClarinets_Poly__ctx_type_0 &_output_){
   synthSamplerClarinets_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Poly_synthSetModulatorTargetLevel(synthSamplerClarinets_Poly__ctx_type_0 &_ctx, uint8_t targetLevel){
}

typedef synthSamplerClarinets_Poly__ctx_type_0 synthSamplerClarinets_Poly_synthSetModulatorPhaseShift_type;

static_inline void synthSamplerClarinets_Poly_synthSetModulatorPhaseShift_init(synthSamplerClarinets_Poly__ctx_type_0 &_output_){
   synthSamplerClarinets_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Poly_synthSetModulatorPhaseShift(synthSamplerClarinets_Poly__ctx_type_0 &_ctx, fix16_t ratio){
}

typedef synthSamplerClarinets_Poly__ctx_type_0 synthSamplerClarinets_Poly_synthSetModulatorFeedback_type;

static_inline void synthSamplerClarinets_Poly_synthSetModulatorFeedback_init(synthSamplerClarinets_Poly__ctx_type_0 &_output_){
   synthSamplerClarinets_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Poly_synthSetModulatorFeedback(synthSamplerClarinets_Poly__ctx_type_0 &_ctx, fix16_t ratio){
}

typedef synthSamplerClarinets_Poly__ctx_type_0 synthSamplerClarinets_Poly_synthSetModulatorADSR_type;

static_inline void synthSamplerClarinets_Poly_synthSetModulatorADSR_init(synthSamplerClarinets_Poly__ctx_type_0 &_output_){
   synthSamplerClarinets_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Poly_synthSetModulatorADSR(synthSamplerClarinets_Poly__ctx_type_0 &_ctx, fix16_t a, fix16_t d, fix16_t s, fix16_t r){
}

typedef synthSamplerClarinets_Poly__ctx_type_0 synthSamplerClarinets_Poly_synthSetCarrierADSR_type;

static_inline void synthSamplerClarinets_Poly_synthSetCarrierADSR_init(synthSamplerClarinets_Poly__ctx_type_0 &_output_){
   synthSamplerClarinets_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Poly_synthSetCarrierADSR(synthSamplerClarinets_Poly__ctx_type_0 &_ctx, fix16_t a, fix16_t d, fix16_t s, fix16_t r){
}

typedef synthSamplerClarinets_Poly__ctx_type_0 synthSamplerClarinets_Poly_shouldLeftOvers_type;

static_inline void synthSamplerClarinets_Poly_shouldLeftOvers_init(synthSamplerClarinets_Poly__ctx_type_0 &_output_){
   synthSamplerClarinets_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline uint8_t synthSamplerClarinets_Poly_shouldLeftOvers(synthSamplerClarinets_Poly__ctx_type_0 &_ctx){
   return _ctx.should_leftovers;
};

typedef synthSamplerClarinets_Poly__ctx_type_0 synthSamplerClarinets_Poly_default_type;

static_inline void synthSamplerClarinets_Poly_default_init(synthSamplerClarinets_Poly__ctx_type_0 &_output_){
   synthSamplerClarinets_Poly__ctx_type_0_init(_output_);
   return ;
}

void synthSamplerClarinets_Poly_default(synthSamplerClarinets_Poly__ctx_type_0 &_ctx);

typedef struct synthSamplerClarinets_Poly__ctx_type_1 {
   synthSamplerClarinets_Poly__ctx_type_0 _inst179;
} synthSamplerClarinets_Poly__ctx_type_1;

typedef synthSamplerClarinets_Poly__ctx_type_1 synthSamplerClarinets_Poly_dummy_type;

static_inline void synthSamplerClarinets_Poly__ctx_type_1_init(synthSamplerClarinets_Poly__ctx_type_1 &_output_){
   synthSamplerClarinets_Poly__ctx_type_1 _ctx;
   synthSamplerClarinets_Poly__ctx_type_0_init(_ctx._inst179);
   _output_ = _ctx;
   return ;
}

static_inline void synthSamplerClarinets_Poly_dummy_init(synthSamplerClarinets_Poly__ctx_type_1 &_output_){
   synthSamplerClarinets_Poly__ctx_type_1_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Poly_dummy(synthSamplerClarinets_Poly__ctx_type_1 &_ctx){
   fix16_t buff[256];
   synthSamplerClarinets_Buffer_buffer(buff);
   synthSamplerClarinets_Poly_runVoice(_ctx._inst179,0,0,buff);
}

typedef struct synthSamplerClarinets_Voice__ctx_type_0 {
   synthSamplerClarinets_Notes__ctx_type_0 voicesinactive;
   synthSamplerClarinets_Notes__ctx_type_0 voicesactive;
   fix16_t voices_ratio;
   int voices[4];
   synthSamplerClarinets_Poly__ctx_type_0 poly;
   int number_voices;
   int notes[128];
   uint8_t normalize;
   fix16_t leftovers_decay;
   fix16_t leftovers;
   int last_velocities[4];
   fix16_t last_values[4];
   fix16_t fs;
   fix16_t buffer_v3[256];
   fix16_t buffer_v2[256];
   fix16_t buffer_v1[256];
   fix16_t buffer_v0[256];
} synthSamplerClarinets_Voice__ctx_type_0;

typedef synthSamplerClarinets_Voice__ctx_type_0 synthSamplerClarinets_Voice_process_type;

void synthSamplerClarinets_Voice__ctx_type_0_init(synthSamplerClarinets_Voice__ctx_type_0 &_output_);

static_inline void synthSamplerClarinets_Voice_process_init(synthSamplerClarinets_Voice__ctx_type_0 &_output_){
   synthSamplerClarinets_Voice__ctx_type_0_init(_output_);
   return ;
}

fix16_t synthSamplerClarinets_Voice_process(synthSamplerClarinets_Voice__ctx_type_0 &_ctx);

typedef synthSamplerClarinets_Voice__ctx_type_0 synthSamplerClarinets_Voice_process_bufferTo_type;

static_inline void synthSamplerClarinets_Voice_process_bufferTo_init(synthSamplerClarinets_Voice__ctx_type_0 &_output_){
   synthSamplerClarinets_Voice__ctx_type_0_init(_output_);
   return ;
}

void synthSamplerClarinets_Voice_process_bufferTo(synthSamplerClarinets_Voice__ctx_type_0 &_ctx, int nb, fix16_t (&oBuffer)[256]);

typedef synthSamplerClarinets_Voice__ctx_type_0 synthSamplerClarinets_Voice_process_bufferTo_alt_type;

static_inline void synthSamplerClarinets_Voice_process_bufferTo_alt_init(synthSamplerClarinets_Voice__ctx_type_0 &_output_){
   synthSamplerClarinets_Voice__ctx_type_0_init(_output_);
   return ;
}

void synthSamplerClarinets_Voice_process_bufferTo_alt(synthSamplerClarinets_Voice__ctx_type_0 &_ctx, int nb, fix16_t (&oBuffer)[256]);

typedef synthSamplerClarinets_Voice__ctx_type_0 synthSamplerClarinets_Voice_noteOff_type;

static_inline void synthSamplerClarinets_Voice_noteOff_init(synthSamplerClarinets_Voice__ctx_type_0 &_output_){
   synthSamplerClarinets_Voice__ctx_type_0_init(_output_);
   return ;
}

void synthSamplerClarinets_Voice_noteOff(synthSamplerClarinets_Voice__ctx_type_0 &_ctx, int note, int channel);

typedef synthSamplerClarinets_Voice__ctx_type_0 synthSamplerClarinets_Voice_noteOn_type;

static_inline void synthSamplerClarinets_Voice_noteOn_init(synthSamplerClarinets_Voice__ctx_type_0 &_output_){
   synthSamplerClarinets_Voice__ctx_type_0_init(_output_);
   return ;
}

void synthSamplerClarinets_Voice_noteOn(synthSamplerClarinets_Voice__ctx_type_0 &_ctx, int note, int velocity, int channel);

typedef synthSamplerClarinets_Voice__ctx_type_0 synthSamplerClarinets_Voice_setNbVoices_type;

static_inline void synthSamplerClarinets_Voice_setNbVoices_init(synthSamplerClarinets_Voice__ctx_type_0 &_output_){
   synthSamplerClarinets_Voice__ctx_type_0_init(_output_);
   return ;
}

void synthSamplerClarinets_Voice_setNbVoices(synthSamplerClarinets_Voice__ctx_type_0 &_ctx, int nbvoices);

typedef synthSamplerClarinets_Voice__ctx_type_0 synthSamplerClarinets_Voice_setNormalize_type;

static_inline void synthSamplerClarinets_Voice_setNormalize_init(synthSamplerClarinets_Voice__ctx_type_0 &_output_){
   synthSamplerClarinets_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Voice_setNormalize(synthSamplerClarinets_Voice__ctx_type_0 &_ctx, uint8_t flag){
   _ctx.normalize = flag;
};

typedef synthSamplerClarinets_Voice__ctx_type_0 synthSamplerClarinets_Voice_setSamplerate_type;

static_inline void synthSamplerClarinets_Voice_setSamplerate_init(synthSamplerClarinets_Voice__ctx_type_0 &_output_){
   synthSamplerClarinets_Voice__ctx_type_0_init(_output_);
   return ;
}

void synthSamplerClarinets_Voice_setSamplerate(synthSamplerClarinets_Voice__ctx_type_0 &_ctx, fix16_t newFs);

typedef synthSamplerClarinets_Voice__ctx_type_0 synthSamplerClarinets_Voice_synthSetLoop_type;

static_inline void synthSamplerClarinets_Voice_synthSetLoop_init(synthSamplerClarinets_Voice__ctx_type_0 &_output_){
   synthSamplerClarinets_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Voice_synthSetLoop(synthSamplerClarinets_Voice__ctx_type_0 &_ctx, uint8_t flag){
   synthSamplerClarinets_Poly_synthSetLoop(_ctx.poly,flag);
};

typedef synthSamplerClarinets_Voice__ctx_type_0 synthSamplerClarinets_Voice_synthSetLoopStart_type;

static_inline void synthSamplerClarinets_Voice_synthSetLoopStart_init(synthSamplerClarinets_Voice__ctx_type_0 &_output_){
   synthSamplerClarinets_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Voice_synthSetLoopStart(synthSamplerClarinets_Voice__ctx_type_0 &_ctx, int value){
   synthSamplerClarinets_Poly_synthSetLoopStart(_ctx.poly,value);
};

typedef synthSamplerClarinets_Voice__ctx_type_0 synthSamplerClarinets_Voice_synthSetLoopEnd_type;

static_inline void synthSamplerClarinets_Voice_synthSetLoopEnd_init(synthSamplerClarinets_Voice__ctx_type_0 &_output_){
   synthSamplerClarinets_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Voice_synthSetLoopEnd(synthSamplerClarinets_Voice__ctx_type_0 &_ctx, int value){
   synthSamplerClarinets_Poly_synthSetLoopEnd(_ctx.poly,value);
};

typedef synthSamplerClarinets_Voice__ctx_type_0 synthSamplerClarinets_Voice_synthGetLoop_type;

static_inline void synthSamplerClarinets_Voice_synthGetLoop_init(synthSamplerClarinets_Voice__ctx_type_0 &_output_){
   synthSamplerClarinets_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline uint8_t synthSamplerClarinets_Voice_synthGetLoop(synthSamplerClarinets_Voice__ctx_type_0 &_ctx){
   return synthSamplerClarinets_Poly_synthGetLoop(_ctx.poly);
};

typedef synthSamplerClarinets_Voice__ctx_type_0 synthSamplerClarinets_Voice_synthGetLoopStart_type;

static_inline void synthSamplerClarinets_Voice_synthGetLoopStart_init(synthSamplerClarinets_Voice__ctx_type_0 &_output_){
   synthSamplerClarinets_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline int synthSamplerClarinets_Voice_synthGetLoopStart(synthSamplerClarinets_Voice__ctx_type_0 &_ctx){
   return synthSamplerClarinets_Poly_synthGetLoopStart(_ctx.poly);
};

typedef synthSamplerClarinets_Voice__ctx_type_0 synthSamplerClarinets_Voice_synthGetLoopEnd_type;

static_inline void synthSamplerClarinets_Voice_synthGetLoopEnd_init(synthSamplerClarinets_Voice__ctx_type_0 &_output_){
   synthSamplerClarinets_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline int synthSamplerClarinets_Voice_synthGetLoopEnd(synthSamplerClarinets_Voice__ctx_type_0 &_ctx){
   return synthSamplerClarinets_Poly_synthGetLoopEnd(_ctx.poly);
};

typedef synthSamplerClarinets_Voice__ctx_type_0 synthSamplerClarinets_Voice_synthGetSize_type;

static_inline void synthSamplerClarinets_Voice_synthGetSize_init(synthSamplerClarinets_Voice__ctx_type_0 &_output_){
   synthSamplerClarinets_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline int synthSamplerClarinets_Voice_synthGetSize(synthSamplerClarinets_Voice__ctx_type_0 &_ctx){
   return synthSamplerClarinets_Poly_synthGetSize(_ctx.poly);
};

typedef synthSamplerClarinets_Voice__ctx_type_0 synthSamplerClarinets_Voice_synthGetNbWavetables_type;

static_inline void synthSamplerClarinets_Voice_synthGetNbWavetables_init(synthSamplerClarinets_Voice__ctx_type_0 &_output_){
   synthSamplerClarinets_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline int synthSamplerClarinets_Voice_synthGetNbWavetables(synthSamplerClarinets_Voice__ctx_type_0 &_ctx){
   return synthSamplerClarinets_Poly_synthGetNbWavetables(_ctx.poly);
};

typedef synthSamplerClarinets_Voice__ctx_type_0 synthSamplerClarinets_Voice_synthSetModulatorWavetable_type;

static_inline void synthSamplerClarinets_Voice_synthSetModulatorWavetable_init(synthSamplerClarinets_Voice__ctx_type_0 &_output_){
   synthSamplerClarinets_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Voice_synthSetModulatorWavetable(synthSamplerClarinets_Voice__ctx_type_0 &_ctx, fix16_t wavetableIdx){
   synthSamplerClarinets_Poly_synthSetModulatorWavetable(_ctx.poly,wavetableIdx);
};

typedef synthSamplerClarinets_Voice__ctx_type_0 synthSamplerClarinets_Voice_synthSetModulatorWavetablePhase_type;

static_inline void synthSamplerClarinets_Voice_synthSetModulatorWavetablePhase_init(synthSamplerClarinets_Voice__ctx_type_0 &_output_){
   synthSamplerClarinets_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Voice_synthSetModulatorWavetablePhase(synthSamplerClarinets_Voice__ctx_type_0 &_ctx, fix16_t phaseIdx){
   synthSamplerClarinets_Poly_synthSetModulatorWavetablePhase(_ctx.poly,phaseIdx);
};

typedef synthSamplerClarinets_Voice__ctx_type_0 synthSamplerClarinets_Voice_synthSetCarrierWavetable_type;

static_inline void synthSamplerClarinets_Voice_synthSetCarrierWavetable_init(synthSamplerClarinets_Voice__ctx_type_0 &_output_){
   synthSamplerClarinets_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Voice_synthSetCarrierWavetable(synthSamplerClarinets_Voice__ctx_type_0 &_ctx, fix16_t wavetableIdx){
   synthSamplerClarinets_Poly_synthSetCarrierWavetable(_ctx.poly,wavetableIdx);
};

typedef synthSamplerClarinets_Voice__ctx_type_0 synthSamplerClarinets_Voice_synthSetCarrierWavetablePhase_type;

static_inline void synthSamplerClarinets_Voice_synthSetCarrierWavetablePhase_init(synthSamplerClarinets_Voice__ctx_type_0 &_output_){
   synthSamplerClarinets_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Voice_synthSetCarrierWavetablePhase(synthSamplerClarinets_Voice__ctx_type_0 &_ctx, fix16_t phaseIdx){
   synthSamplerClarinets_Poly_synthSetCarrierWavetablePhase(_ctx.poly,phaseIdx);
};

typedef synthSamplerClarinets_Voice__ctx_type_0 synthSamplerClarinets_Voice_synthSetModulatorRatio_type;

static_inline void synthSamplerClarinets_Voice_synthSetModulatorRatio_init(synthSamplerClarinets_Voice__ctx_type_0 &_output_){
   synthSamplerClarinets_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Voice_synthSetModulatorRatio(synthSamplerClarinets_Voice__ctx_type_0 &_ctx, fix16_t ratio){
   synthSamplerClarinets_Poly_synthSetModulatorRatio(_ctx.poly,ratio);
};

typedef synthSamplerClarinets_Voice__ctx_type_0 synthSamplerClarinets_Voice_synthSetCarrierRatio_type;

static_inline void synthSamplerClarinets_Voice_synthSetCarrierRatio_init(synthSamplerClarinets_Voice__ctx_type_0 &_output_){
   synthSamplerClarinets_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Voice_synthSetCarrierRatio(synthSamplerClarinets_Voice__ctx_type_0 &_ctx, fix16_t ratio){
   synthSamplerClarinets_Poly_synthSetCarrierRatio(_ctx.poly,ratio);
};

typedef synthSamplerClarinets_Voice__ctx_type_0 synthSamplerClarinets_Voice_synthSetModulatorLevel_type;

static_inline void synthSamplerClarinets_Voice_synthSetModulatorLevel_init(synthSamplerClarinets_Voice__ctx_type_0 &_output_){
   synthSamplerClarinets_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Voice_synthSetModulatorLevel(synthSamplerClarinets_Voice__ctx_type_0 &_ctx, fix16_t level){
   synthSamplerClarinets_Poly_synthSetModulatorLevel(_ctx.poly,level);
};

typedef synthSamplerClarinets_Voice__ctx_type_0 synthSamplerClarinets_Voice_synthSetModulatorTargetLevel_type;

static_inline void synthSamplerClarinets_Voice_synthSetModulatorTargetLevel_init(synthSamplerClarinets_Voice__ctx_type_0 &_output_){
   synthSamplerClarinets_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Voice_synthSetModulatorTargetLevel(synthSamplerClarinets_Voice__ctx_type_0 &_ctx, uint8_t targetLevel){
   synthSamplerClarinets_Poly_synthSetModulatorTargetLevel(_ctx.poly,targetLevel);
};

typedef synthSamplerClarinets_Voice__ctx_type_0 synthSamplerClarinets_Voice_synthSetModulatorPhaseShift_type;

static_inline void synthSamplerClarinets_Voice_synthSetModulatorPhaseShift_init(synthSamplerClarinets_Voice__ctx_type_0 &_output_){
   synthSamplerClarinets_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Voice_synthSetModulatorPhaseShift(synthSamplerClarinets_Voice__ctx_type_0 &_ctx, fix16_t ratio){
   synthSamplerClarinets_Poly_synthSetModulatorPhaseShift(_ctx.poly,ratio);
};

typedef synthSamplerClarinets_Voice__ctx_type_0 synthSamplerClarinets_Voice_synthSetModulatorFeedback_type;

static_inline void synthSamplerClarinets_Voice_synthSetModulatorFeedback_init(synthSamplerClarinets_Voice__ctx_type_0 &_output_){
   synthSamplerClarinets_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Voice_synthSetModulatorFeedback(synthSamplerClarinets_Voice__ctx_type_0 &_ctx, fix16_t ratio){
   synthSamplerClarinets_Poly_synthSetModulatorFeedback(_ctx.poly,ratio);
};

typedef synthSamplerClarinets_Voice__ctx_type_0 synthSamplerClarinets_Voice_synthSetModulatorADSR_type;

static_inline void synthSamplerClarinets_Voice_synthSetModulatorADSR_init(synthSamplerClarinets_Voice__ctx_type_0 &_output_){
   synthSamplerClarinets_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Voice_synthSetModulatorADSR(synthSamplerClarinets_Voice__ctx_type_0 &_ctx, fix16_t a, fix16_t d, fix16_t s, fix16_t r){
   synthSamplerClarinets_Poly_synthSetModulatorADSR(_ctx.poly,a,d,s,r);
};

typedef synthSamplerClarinets_Voice__ctx_type_0 synthSamplerClarinets_Voice_synthSetCarrierADSR_type;

static_inline void synthSamplerClarinets_Voice_synthSetCarrierADSR_init(synthSamplerClarinets_Voice__ctx_type_0 &_output_){
   synthSamplerClarinets_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Voice_synthSetCarrierADSR(synthSamplerClarinets_Voice__ctx_type_0 &_ctx, fix16_t a, fix16_t d, fix16_t s, fix16_t r){
   synthSamplerClarinets_Poly_synthSetCarrierADSR(_ctx.poly,a,d,s,r);
};

typedef synthSamplerClarinets_Voice__ctx_type_0 synthSamplerClarinets_Voice_default_type;

static_inline void synthSamplerClarinets_Voice_default_init(synthSamplerClarinets_Voice__ctx_type_0 &_output_){
   synthSamplerClarinets_Voice__ctx_type_0_init(_output_);
   return ;
}

void synthSamplerClarinets_Voice_default(synthSamplerClarinets_Voice__ctx_type_0 &_ctx);

typedef struct synthSamplerClarinets_Voice__ctx_type_1 {
   synthSamplerClarinets_Voice__ctx_type_0 _inst275;
   synthSamplerClarinets_Voice__ctx_type_0 _inst1b9;
} synthSamplerClarinets_Voice__ctx_type_1;

typedef synthSamplerClarinets_Voice__ctx_type_1 synthSamplerClarinets_Voice_dummy_type;

void synthSamplerClarinets_Voice__ctx_type_1_init(synthSamplerClarinets_Voice__ctx_type_1 &_output_);

static_inline void synthSamplerClarinets_Voice_dummy_init(synthSamplerClarinets_Voice__ctx_type_1 &_output_){
   synthSamplerClarinets_Voice__ctx_type_1_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Voice_dummy(synthSamplerClarinets_Voice__ctx_type_1 &_ctx){
   fix16_t buff[256];
   synthSamplerClarinets_Buffer_buffer(buff);
   synthSamplerClarinets_Voice_process_bufferTo(_ctx._inst1b9,0,buff);
   synthSamplerClarinets_Voice_process_bufferTo_alt(_ctx._inst275,0,buff);
}

int synthSamplerClarinets_Processor_cvToPitch(fix16_t cv);

static_inline fix16_t synthSamplerClarinets_Processor_bool2real(uint8_t b){
   if(b){
      return 0x10000 /* 1.000000 */;
   }
   else
   {
      return 0x0 /* 0.000000 */;
   }
};

typedef struct synthSamplerClarinets_Processor__ctx_type_2 {
   synthSamplerClarinets_Voice__ctx_type_0 voice;
   int last_pitches[16];
   int last_nbcables;
   uint8_t last_gates[16];
   fix16_t fs;
   synthSamplerClarinets_Util__ctx_type_3 _inst193b;
   synthSamplerClarinets_Util__ctx_type_3 _inst163b;
   synthSamplerClarinets_Util__ctx_type_3 _inst133b;
} synthSamplerClarinets_Processor__ctx_type_2;

typedef synthSamplerClarinets_Processor__ctx_type_2 synthSamplerClarinets_Processor_process_type;

void synthSamplerClarinets_Processor__ctx_type_2_init(synthSamplerClarinets_Processor__ctx_type_2 &_output_);

static_inline void synthSamplerClarinets_Processor_process_init(synthSamplerClarinets_Processor__ctx_type_2 &_output_){
   synthSamplerClarinets_Processor__ctx_type_2_init(_output_);
   return ;
}

static_inline fix16_t synthSamplerClarinets_Processor_process(synthSamplerClarinets_Processor__ctx_type_2 &_ctx){
   return synthSamplerClarinets_Voice_process(_ctx.voice);
};

typedef synthSamplerClarinets_Processor__ctx_type_2 synthSamplerClarinets_Processor_setNote_type;

static_inline void synthSamplerClarinets_Processor_setNote_init(synthSamplerClarinets_Processor__ctx_type_2 &_output_){
   synthSamplerClarinets_Processor__ctx_type_2_init(_output_);
   return ;
}

void synthSamplerClarinets_Processor_setNote(synthSamplerClarinets_Processor__ctx_type_2 &_ctx, fix16_t gate, fix16_t voct, fix16_t vel, int cable);

typedef synthSamplerClarinets_Processor__ctx_type_2 synthSamplerClarinets_Processor_nbCables_type;

static_inline void synthSamplerClarinets_Processor_nbCables_init(synthSamplerClarinets_Processor__ctx_type_2 &_output_){
   synthSamplerClarinets_Processor__ctx_type_2_init(_output_);
   return ;
}

void synthSamplerClarinets_Processor_nbCables(synthSamplerClarinets_Processor__ctx_type_2 &_ctx, int nbcables);

typedef synthSamplerClarinets_Processor__ctx_type_2 synthSamplerClarinets_Processor_setSamplerate_type;

static_inline void synthSamplerClarinets_Processor_setSamplerate_init(synthSamplerClarinets_Processor__ctx_type_2 &_output_){
   synthSamplerClarinets_Processor__ctx_type_2_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Processor_setSamplerate(synthSamplerClarinets_Processor__ctx_type_2 &_ctx, fix16_t newFs){
   if((newFs > 0x0 /* 0.000000 */) && (newFs != _ctx.fs)){
      _ctx.fs = newFs;
      synthSamplerClarinets_Voice_setSamplerate(_ctx.voice,_ctx.fs);
   }
};

typedef synthSamplerClarinets_Processor__ctx_type_2 synthSamplerClarinets_Processor_setLoop_type;

static_inline void synthSamplerClarinets_Processor_setLoop_init(synthSamplerClarinets_Processor__ctx_type_2 &_output_){
   synthSamplerClarinets_Processor__ctx_type_2_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Processor_setLoop(synthSamplerClarinets_Processor__ctx_type_2 &_ctx, uint8_t param, uint8_t force){
   if(synthSamplerClarinets_Util_change(_ctx._inst133b,synthSamplerClarinets_Processor_bool2real(param)) || force){
      synthSamplerClarinets_Voice_synthSetLoop(_ctx.voice,param);
   }
};

typedef synthSamplerClarinets_Processor__ctx_type_2 synthSamplerClarinets_Processor_setLoopStart_type;

static_inline void synthSamplerClarinets_Processor_setLoopStart_init(synthSamplerClarinets_Processor__ctx_type_2 &_output_){
   synthSamplerClarinets_Processor__ctx_type_2_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Processor_setLoopStart(synthSamplerClarinets_Processor__ctx_type_2 &_ctx, int param, uint8_t force){
   if(synthSamplerClarinets_Util_change(_ctx._inst163b,int_to_fix(param)) || force){
      synthSamplerClarinets_Voice_synthSetLoopStart(_ctx.voice,param);
   }
};

typedef synthSamplerClarinets_Processor__ctx_type_2 synthSamplerClarinets_Processor_setLoopEnd_type;

static_inline void synthSamplerClarinets_Processor_setLoopEnd_init(synthSamplerClarinets_Processor__ctx_type_2 &_output_){
   synthSamplerClarinets_Processor__ctx_type_2_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Processor_setLoopEnd(synthSamplerClarinets_Processor__ctx_type_2 &_ctx, int param, uint8_t force){
   if(synthSamplerClarinets_Util_change(_ctx._inst193b,int_to_fix(param)) || force){
      synthSamplerClarinets_Voice_synthSetLoopEnd(_ctx.voice,param);
   }
};

typedef synthSamplerClarinets_Processor__ctx_type_2 synthSamplerClarinets_Processor_getLoop_type;

static_inline void synthSamplerClarinets_Processor_getLoop_init(synthSamplerClarinets_Processor__ctx_type_2 &_output_){
   synthSamplerClarinets_Processor__ctx_type_2_init(_output_);
   return ;
}

static_inline uint8_t synthSamplerClarinets_Processor_getLoop(synthSamplerClarinets_Processor__ctx_type_2 &_ctx){
   return synthSamplerClarinets_Voice_synthGetLoop(_ctx.voice);
};

typedef synthSamplerClarinets_Processor__ctx_type_2 synthSamplerClarinets_Processor_getLoopStart_type;

static_inline void synthSamplerClarinets_Processor_getLoopStart_init(synthSamplerClarinets_Processor__ctx_type_2 &_output_){
   synthSamplerClarinets_Processor__ctx_type_2_init(_output_);
   return ;
}

static_inline int synthSamplerClarinets_Processor_getLoopStart(synthSamplerClarinets_Processor__ctx_type_2 &_ctx){
   return synthSamplerClarinets_Voice_synthGetLoopStart(_ctx.voice);
};

typedef synthSamplerClarinets_Processor__ctx_type_2 synthSamplerClarinets_Processor_getLoopEnd_type;

static_inline void synthSamplerClarinets_Processor_getLoopEnd_init(synthSamplerClarinets_Processor__ctx_type_2 &_output_){
   synthSamplerClarinets_Processor__ctx_type_2_init(_output_);
   return ;
}

static_inline int synthSamplerClarinets_Processor_getLoopEnd(synthSamplerClarinets_Processor__ctx_type_2 &_ctx){
   return synthSamplerClarinets_Voice_synthGetLoopEnd(_ctx.voice);
};

typedef synthSamplerClarinets_Processor__ctx_type_2 synthSamplerClarinets_Processor_getSize_type;

static_inline void synthSamplerClarinets_Processor_getSize_init(synthSamplerClarinets_Processor__ctx_type_2 &_output_){
   synthSamplerClarinets_Processor__ctx_type_2_init(_output_);
   return ;
}

static_inline int synthSamplerClarinets_Processor_getSize(synthSamplerClarinets_Processor__ctx_type_2 &_ctx){
   return synthSamplerClarinets_Voice_synthGetSize(_ctx.voice);
};

typedef synthSamplerClarinets_Processor__ctx_type_2 synthSamplerClarinets_Processor_default_type;

static_inline void synthSamplerClarinets_Processor_default_init(synthSamplerClarinets_Processor__ctx_type_2 &_output_){
   synthSamplerClarinets_Processor__ctx_type_2_init(_output_);
   return ;
}

static_inline void synthSamplerClarinets_Processor_default(synthSamplerClarinets_Processor__ctx_type_2 &_ctx){
   synthSamplerClarinets_Voice_default(_ctx.voice);
   synthSamplerClarinets_Processor_setSamplerate(_ctx,0x2c1999 /* 44.100000 */);
}



#endif // ENGINE_SYNTHSAMPLERCLARINETS_H
